# Script to only analyse sleep restriction condition

library("stringr")
library("lavaan")
library("DiagrammeR")
library("dplyr")
library("semPlot")
library("readr")



modelData_sd <- read_csv("~/Desktop/SleepyBrain-Analyses/Sleepmeasures_emotion/Data/SEM_file_sd.csv") ;
modelData_nsd <- read_csv("~/Desktop/SleepyBrain-Analyses/Sleepmeasures_emotion/Data/SEM_file_nsd.csv") ;
modelData <- merge(modelData_sd, modelData_nsd, by = c("Subject", "Sex", "AgeGroup"))
colnames(modelData) <- c("Subject", "Sex", "AgeGroup", "X1.x", "DeprivationCondition.sd",
                         "Unp.sd", "C_ang.sd", "C_hap.sd", "Upreg.sd", "Downr.sd", "TST_fullsleep.sd",
                         "SWS_fullsleep.sd", "REM_fullsleep.sd", "Sleepiness_KSS.sd", "PANAS_Negative_sleepdeprived",
                         "PANAS_Positive_sleepdeprived", "X1.y", "DeprivationCondition.nsd", "Unp.nsd", "C_ang.nsd", "C_hap.nsd", "Upreg.nsd", "Downr.nsd", "TST_fullsleep.nsd",
                         "SWS_fullsleep.nsd", "REM_fullsleep.nsd", "Sleepiness_KSS.nsd",
                         "PANAS_Negative_fullsleep", "PANAS_Positive_fullsleep")

write.csv2(modelData, "~/Desktop/SleepyBrain-Analyses/Sleepmeasures_emotion/Data/SEM_file_wide.csv")

#
# This model specification was automatically generated by Onyx
#
model<-"
! regressions 
Empathy=~1.0*Unp.nsd
Empathy=~1.0*Unp.sd
Emotional_regulation=~1.0*Upreg.sd
Emotional_regulation=~1.0*Downr.sd
Emotional_regulation=~1.0*Upreg.nsd
Emotional_regulation=~1.0*Downr.nsd
Emotional_Contagion=~1.0*C_ang.sd
Emotional_Contagion=~1.0*C_hap.sd
Emotional_Contagion=~1.0*C_hap.nsd
Emotional_Contagion=~1.0*C_ang.nsd
! residuals, variances and covariances
Empathy ~~ VAR_Empathy*Empathy
Emotional_regulation ~~ VAR_Emotional_regulation*Emotional_regulation
Emotional_Contagion ~~ VAR_Emotional_Contagion*Emotional_Contagion
Emotional_Contagion ~~ 1.0*Emotional_regulation
Empathy ~~ 1.0*Emotional_regulation
Empathy ~~ 1.0*Emotional_Contagion
Unp.sd ~~ VAR_Unp.sd*Unp.sd
Unp.nsd ~~ VAR_Unp.nsd*Unp.nsd
Upreg.sd ~~ VAR_Upreg.sd*Upreg.sd
Downr.sd ~~ VAR_Downr.sd*Downr.sd
Upreg.nsd ~~ VAR_Upreg.nsd*Upreg.nsd
Downr.nsd ~~ VAR_Downr.nsd*Downr.nsd
C_ang.nsd ~~ VAR_C_ang.nsd*C_ang.nsd
C_hap.nsd ~~ VAR_C_hap.nsd*C_hap.nsd
C_ang.sd ~~ VAR_C_ang.sd*C_ang.sd
C_hap.sd ~~ VAR_C_hap.sd*C_hap.sd
! observed means
Unp.sd~1;
Unp.nsd~1;
Upreg.sd~1;
Downr.sd~1;
Upreg.nsd~1;
Downr.nsd~1;
C_ang.nsd~1;
C_hap.nsd~1;
C_ang.sd~1;
C_hap.sd~1;
";
result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result, fit.measures=TRUE);

summary(result, fit.measures=TRUE);
sink("Singer_SEM_sd_ratings.txt")
summary(result, fit.measures=T);
sink()

# Plot path diagram:
fit <- lavaan:::cfa(model, data = modelData, missing="FIML")

semPaths(fit, intercept = F, whatLabel = "est", nCharNodes = 0, nCharEdges =0, sizeMan = 5,
         exoVar = F,
         #groups = list(c("Ep", "Unp"), 
         #               c("EC", "C_Ang", "C_hap"),
         #              c("ER", "Downr", "Upreg")),
         residuals = T, exoCov = T, layout = "tree", ask = F, as.expression = "edges", fixedStyle = c("black",3),
         pastel = T)

# Parameter estimates
parameterEstimates(result)
# Standardized estimates
standardizedSolution(result)
