# Script to write data file for analyses of seed-based connectivity and effects of KSS
# Reads files with roi time-series generated by DPARSFA, merges with other data, writes files suitable for analysis in R

# Read files
files_S1 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISignals_151110/FunImgARWSDFCB_ROISignals", pattern = c("ROISignals", ".txt"))
files_S1 <- files_S1[(seq(2, 106, 2))] # Workaround to get only .txt files
signals_S1 <- list()
for (i in 1:length(files_S1)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110/FunImgARWSDFCB_ROISignals/", files_S1[i], sep = ""))
  signals_S1[[i]] <- data
}

files_S2 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110/S2_FunImgARWSDFCB_ROISignals", pattern = c("ROISignals", ".txt"))
files_S2 <- files_S2[(seq(2, 106, 2))] # Workaround to get only .txt files
signals_S2 <- list()
for (i in 1:length(files_S2)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110/S2_FunImgARWSDFCB_ROISignals/", files_S2[i], sep = ""))
  signals_S2[[i]] <- data
}

files_S3 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISignals_151110/S3_FunImgARWSDFCB_ROISignals", pattern = c("ROISignals", ".txt"))
files_S3 <- files_S3[(seq(2, 106, 2))] # Workaround to get only .txt files
signals_S3 <- list()
for (i in 1:length(files_S3)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110/S3_FunImgARWSDFCB_ROISignals/", files_S3[i], sep = ""))
  signals_S3[[i]] <- data
}

files_S4 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110/S4_FunImgARWSDFCB_ROISignals", pattern = c("ROISignals", ".txt"))
files_S4 <- files_S4[(seq(2, 106, 2))] # Workaround to get only .txt files
signals_S4 <- list()
for (i in 1:length(files_S4)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110/S4_FunImgARWSDFCB_ROISignals/", files_S4[i], sep = ""))
  signals_S4[[i]] <- data
}

# Read files with framewise displacement data, also generated from DPARSFA
FDfiles <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/RealignParameter_RestingState_151001")
subjectfolders <- FDfiles[seq(1, 106, 2)]
FD_S1 <- vector("list", length = 53)
FD_S2 <- vector("list", length = 53)
FD_S3 <- vector("list", length = 53)
FD_S4 <- vector("list", length = 53)
j <- 1
for (i in subjectfolders){
  FD_S1[[j]] <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/RealignParameter_RestingState_151001/", i, "/FD_Power_", i, ".txt", sep = ""), quote="\"")
  FD_S2[[j]] <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/RealignParameter_RestingState_151001/", i, "/S2_FD_Power_", i, ".txt", sep = ""), quote="\"")
  FD_S3[[j]] <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/RealignParameter_RestingState_151001/", i, "/S3_FD_Power_", i, ".txt", sep = ""), quote="\"")
  FD_S4[[j]] <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/RealignParameter_RestingState_151001/", i, "/S4_FD_Power_", i, ".txt", sep = ""), quote="\"")
  j <- j +1
}

require(R.matlab)
test <- readMat("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/ROISignals_151110/ROI_List_151110.mat")

########################

# Read data files for analysis covariates
subjects <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/Subjects_RestingState_151110.csv")
demdata <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/150215_Demographic.csv")
demdata <- merge(subjects, demdata, by.x = "subject", by.y = "Subject")
randlist <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/RandomisationList_140804.csv")
demdata <- merge(demdata, randlist, by.x = "subject", by.y = "Subject")
demdata$Sl_cond_binary <- demdata$Sl_cond -1
#FDdata <- read.table("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/RealignParameter_RestingState_151001/n_excluded.txt", header = T) # Framewise displacement, data say how many volumes had FD > 0.5 and were interpolated

# Read data files for KSS as covariates
KSSfolders <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles")
KSSfolders <- data.frame(folder = KSSfolders, subject = as.integer(substring(KSSfolders, 1, 3)))
KSSfolders <- KSSfolders[KSSfolders$subject %in% subjects$subject, ]

KSSvectors <- list()
for (i in 1:length(KSSfolders$folder)){
  KSSratings <- read.delim(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles/", KSSfolders$folder[i], "/KSS.txt", sep = ""), skip = 1, header = F)
  KSSlog <- read.delim(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles/", KSSfolders$folder[i], "/Sleepiness_sce.log", sep = ""), skip = 5, header = F)
  responses <- which(KSSlog[, 2] == "Response")
  length_responses <- length(responses)
  volumestoremove <- vector()
  for(j in responses){
    pulsesbeforeresponse <- sum(KSSlog[1:j, 2] == "Pulse")
    vols <- c(volumestoremove, pulsesbeforeresponse - 1, pulsesbeforeresponse, pulsesbeforeresponse + 1, pulsesbeforeresponse + 2, pulsesbeforeresponse + 3, pulsesbeforeresponse + 4, pulsesbeforeresponse + 5)
    volumestoremove <- unique(vols)
  }
  segment1 <- min(volumestoremove) - 4 
  segment2 <- min(volumestoremove[volumestoremove >= 80]) - max(volumestoremove[volumestoremove <= 80]) # These break points (80 and 120) are a pragmatic workaround, as they are expected to always fall in intervals between ratings
  segment3 <- min(volumestoremove[volumestoremove >= 120]) - max(volumestoremove[volumestoremove <= 120])
  segment4 <- 163 - (segment1 + segment2 + segment3)
  
  KSSvectors[[i]] <- c(rep(KSSratings[1, 1], segment1), rep(KSSratings[2, 1], segment2), rep(KSSratings[3, 1], segment3), rep(KSSratings[4, 1], segment4))
}

KSS_S3 <- KSSvectors[seq(1, 105, 2)]
KSS_S4 <- KSSvectors[seq(2, 106, 2)]

#######################

# Make one big dataframe with roi timecourses and covariates

S1 <- do.call(rbind, signals_S1)
S1$session <- "S1"
S1$subject <- rep(subjects$subject, each = 163)
S1$kss <- NA
S1$condition <- "deprived"
S1$volno <- 1:163
S1 <- merge(S1, randlist[, 1:2], by.x = "subject", by.y = "Subject")
S1$condition[S1$Sl_cond == 2] <- "full"
df_FD_S1 <- do.call(rbind, FD_S1)
S1$FD <- df_FD_S1$V1

S2 <- do.call(rbind, signals_S2)
S2$session <- "S2"
S2$subject <- rep(subjects$subject, each = 163)
S2$kss <- NA
S2$condition <- "deprived"
S2$volno <- 1:163
S2 <- merge(S2, randlist[, 1:2], by.x = "subject", by.y = "Subject")
S2$condition[S2$Sl_cond == 1] <- "full"
df_FD_S2 <- do.call(rbind, FD_S2)
S2$FD <- df_FD_S2$V1

S3 <- do.call(rbind, signals_S3)
S3$session <- "S3"
S3$subject <- rep(subjects$subject, each = 163)
S3$kss <- unlist(KSS_S3)
S3$condition <- "deprived"
S3$volno <- 1:163
S3 <- merge(S3, randlist[, 1:2], by.x = "subject", by.y = "Subject")
S3$condition[S3$Sl_cond == 2] <- "full"
df_FD_S3 <- do.call(rbind, FD_S3)
S3$FD <- df_FD_S3$V1

S4 <- do.call(rbind, signals_S4)
S4$session <- "S4"
S4$subject <- rep(subjects$subject, each = 163)
S4$kss <- unlist(KSS_S4)
S4$condition <- "deprived"
S4$volno <- 1:163
S4 <- merge(S4, randlist[, 1:2], by.x = "subject", by.y = "Subject")
S4$condition[S4$Sl_cond == 1] <- "full"
df_FD_S4 <- do.call(rbind, FD_S4)
S4$FD <- df_FD_S4$V1

data <- do.call("rbind", list(S1, S2, S3, S4))
data <- merge(data, demdata[, c("subject", "AgeGroup")])

data$session <- as.factor(data$session)
data$condition <- as.factor(data$condition)

dummyID <- read.csv("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Subjects_151215.csv", sep=";")

data <- merge(data, dummyID[, c("Subject", "newid")], by.x = "subject", by.y = "Subject")
data <- subset(data, select = -c(subject, Sl_cond))
data <- data[with(data, order(newid, session)), ]

write.csv(data, "C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/resting_roi_connectivity_160408.csv", row.names = F)


# Do the whole thing again, this time with data that have been through global signal regression
files_S1b <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISignals_151110b/FunImgARWSDFCB_ROISignals", pattern = c("ROISignals", ".txt"))
files_S1b <- files_S1b[(seq(2, 106, 2))] # Workaround to get only .txt files
signals_S1b <- list()
for (i in 1:length(files_S1b)){
  datab <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110b/FunImgARWSDFCB_ROISignals/", files_S1b[i], sep = ""))
  signals_S1b[[i]] <- datab
}

files_S2b <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110b/S2_FunImgARWSDFCB_ROISignals", pattern = c("ROISignals", ".txt"))
files_S2b <- files_S2b[(seq(2, 106, 2))] # Workaround to get only .txt files
signals_S2b <- list()
for (i in 1:length(files_S2b)){
  datab <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110b/S2_FunImgARWSDFCB_ROISignals/", files_S2b[i], sep = ""))
  signals_S2b[[i]] <- datab
}

files_S3b <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISignals_151110b/S3_FunImgARWSDFCB_ROISignals", pattern = c("ROISignals", ".txt"))
files_S3b <- files_S3b[(seq(2, 106, 2))] # Workaround to get only .txt files
signals_S3b <- list()
for (i in 1:length(files_S3b)){
  datab <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110b/S3_FunImgARWSDFCB_ROISignals/", files_S3b[i], sep = ""))
  signals_S3b[[i]] <- datab
}

files_S4b <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110b/S4_FunImgARWSDFCB_ROISignals", pattern = c("ROISignals", ".txt"))
files_S4b <- files_S4b[(seq(2, 106, 2))] # Workaround to get only .txt files
signals_S4b <- list()
for (i in 1:length(files_S4b)){
  datab <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/ROISIgnals_151110b/S4_FunImgARWSDFCB_ROISignals/", files_S4b[i], sep = ""))
  signals_S4b[[i]] <- datab
}


S1b <- do.call(rbind, signals_S1b)
S1b$session <- "S1"
S1b$subject <- rep(subjects$subject, each = 163)
S1b$kss <- NA
S1b$condition <- "deprived"
S1b$volno <- 1:163
S1b <- merge(S1b, randlist[, 1:2], by.x = "subject", by.y = "Subject")
S1b$condition[S1b$Sl_cond == 2] <- "full"
S1b$FD <- df_FD_S1$V1

S2b <- do.call(rbind, signals_S2b)
S2b$session <- "S2"
S2b$subject <- rep(subjects$subject, each = 163)
S2b$kss <- NA
S2b$condition <- "deprived"
S2b$volno <- 1:163
S2b <- merge(S2b, randlist[, 1:2], by.x = "subject", by.y = "Subject")
S2b$condition[S2b$Sl_cond == 1] <- "full"
S2b$FD <- df_FD_S2$V1

S3b <- do.call(rbind, signals_S3b)
S3b$session <- "S3"
S3b$subject <- rep(subjects$subject, each = 163)
S3b$kss <- unlist(KSS_S3)
S3b$condition <- "deprived"
S3b$volno <- 1:163
S3b <- merge(S3b, randlist[, 1:2], by.x = "subject", by.y = "Subject")
S3b$condition[S3b$Sl_cond == 2] <- "full"
S3b$FD <- df_FD_S3$V1

S4b <- do.call(rbind, signals_S4b)
S4b$session <- "S4"
S4b$subject <- rep(subjects$subject, each = 163)
S4b$kss <- unlist(KSS_S4)
S4b$condition <- "deprived"
S4b$volno <- 1:163
S4b <- merge(S4b, randlist[, 1:2], by.x = "subject", by.y = "Subject")
S4b$condition[S4b$Sl_cond == 1] <- "full"
S4b$FD <- df_FD_S4$V1

datab <- do.call("rbind", list(S1b, S2b, S3b, S4b))
datab <- merge(datab, demdata[, c("subject", "AgeGroup")])

datab$session <- as.factor(datab$session)
datab$condition <- as.factor(datab$condition)

datab <- merge(datab, dummyID[, c("Subject", "newid")], by.x = "subject", by.y = "Subject")
datab <- subset(datab, select = -c(subject, Sl_cond))
datab <- datab[with(datab, order(newid, session)), ]

write.csv(datab, "C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/resting_roi_connectivity_160408_GSR.csv", row.names = F)
