# Script to analyse global signal amplitude

# Read files
# The files contain nuisance regressors, including motion and total signal from GM, WM, and CSF, generated by DPARSFA
files_S1 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/FunImgARWSDFCovs", pattern = c("Covariables", ".txt"))
files_S1 <- files_S1[(seq(2, 106, 2))] # Workaround to get only .txt files
covs_S1 <- list()
for (i in 1:length(files_S1)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/FunImgARWSDFCovs/", files_S1[i], sep = ""))
  covs_S1[[i]] <- data$V10
}

files_S2 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S2_FunImgARWSDFCovs", pattern = c("Covariables", ".txt"))
files_S2 <- files_S2[(seq(2, 106, 2))] # Workaround to get only .txt files
covs_S2 <- list()
for (i in 1:length(files_S2)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S2_FunImgARWSDFCovs/", files_S2[i], sep = ""))
  covs_S2[[i]] <- data$V10
}

files_S3 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S3_FunImgARWSDFCovs", pattern = c("Covariables", ".txt"))
files_S3 <- files_S3[(seq(2, 106, 2))] # Workaround to get only .txt files
covs_S3 <- list()
for (i in 1:length(files_S3)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S3_FunImgARWSDFCovs/", files_S3[i], sep = ""))
  covs_S3[[i]] <- data$V10
}

files_S4 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S4_FunImgARWSDFCovs", pattern = c("Covariables", ".txt"))
files_S4 <- files_S4[(seq(2, 106, 2))] # Workaround to get only .txt files
covs_S4 <- list()
for (i in 1:length(files_S4)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S4_FunImgARWSDFCovs/", files_S4[i], sep = ""))
  covs_S4[[i]] <- data$V10
}

########################

# Calculate global signal amplitude and other measures and put in data frame
fun_rms <- function(x) sqrt(mean(x^2))

data_glob <- data.frame(
  ID = rep(1:53, 4),
  session = c(rep(1, 53), rep(2, 53), rep(3, 53), rep(4, 53)),
  globalsignal = c(unlist(lapply(covs_S1, mean)), unlist(lapply(covs_S2, mean)), unlist(lapply(covs_S3, mean)), unlist(lapply(covs_S4, mean))),
  globalsignal_rms = c(unlist(lapply(covs_S1, fun_rms)), unlist(lapply(covs_S2, fun_rms)), unlist(lapply(covs_S3, fun_rms)), unlist(lapply(covs_S4, fun_rms))),
  globalsignal_sd = c(unlist(lapply(covs_S1, sd)), unlist(lapply(covs_S2, sd)), unlist(lapply(covs_S3, sd)), unlist(lapply(covs_S4, sd)))
)

hist(data_glob$globalsignal)
hist(data_glob$globalsignal_rms)
hist(data_glob$globalsignal_sd)
hist(log(data_glob$globalsignal_sd))

data_glob$globalsignal_logsd <- log(data_glob$globalsignal_sd) # Log transform to achieve a more normal distribution

gs <- c(unlist(covs_S1), unlist(covs_S2), unlist(covs_S3), unlist(covs_S4))
hist(gs)

########################

# Read data files for randomisation list etc, make final data frame
subjects <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/Subjects_RestingState_151110.csv")
demdata <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/150215_Demographic.csv")
demdata <- merge(subjects, demdata, by.x = "subject", by.y = "Subject")
randlist <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/RandomisationList_140804.csv")
demdata <- merge(demdata, randlist, by.x = "subject", by.y = "Subject")
FDdata <- read.table("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/RealignParameter_RestingState_151001/n_excluded.txt", header = T) # Framewise displacement, data say how many volumes had FD > 0.5 and were interpolated
FDdata <- reshape(FDdata, direction = "long", varying = c("S1", "S2", "S3", "S4"), idvar = "subject", v.names = "FD")
FDdata <- FDdata[with(FDdata, order(subject, time)), ]

data_glob <- merge(data_glob, subjects, by = "ID")
data_glob <- merge(data_glob, randlist[, 1:2], by.x = "subject", by.y = "Subject")

data_glob$condition <- "fullsleep"
data_glob$condition[data_glob$session == 1 & data_glob$Sl_cond == 1] <- "sleepdeprived"
data_glob$condition[data_glob$session == 3 & data_glob$Sl_cond == 1] <- "sleepdeprived"
data_glob$condition[data_glob$session == 2 & data_glob$Sl_cond == 2] <- "sleepdeprived"
data_glob$condition[data_glob$session == 4 & data_glob$Sl_cond == 2] <- "sleepdeprived"

data_glob <- merge(data_glob, demdata)
data_glob <- merge(data_glob, FDdata, by.x = c("subject", "session"), by.y = c("subject", "time"))

# Read KSS data
KSSfolders <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles")
KSSfolders <- data.frame(folder = KSSfolders, subject = as.integer(substring(KSSfolders, 1, 3)))
KSSfolders <- KSSfolders[KSSfolders$subject %in% subjects$subject, ]
kssdata <- data.frame(folder = NULL, kss2 = NULL, kss69 = NULL)
for (i in 1:length(KSSfolders$folder)){
  KSSratings2 <- read.delim(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles/", KSSfolders$folder[i], "/KSS_brief2.txt", sep = ""), skip = 1, header = F)
  KSSratings6_9 <- read.delim(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles/", KSSfolders$folder[i], "/KSS.txt", sep = ""), skip = 1, header = F)
  KSSratings6_9 <- mean(KSSratings6_9$V1)
  data <- data.frame(folder = KSSfolders$folder[i], kss2 = as.integer(KSSratings2), kss69 = KSSratings6_9)
  kssdata <- rbind(kssdata, data)
}

boxplot(kssdata$kss2, kssdata$kss69)
t.test(kssdata$kss2, kssdata$kss69)

kssdata$subject <- substring(kssdata$folder, 1, 3)
kssdata$sessionpair <- c("1_3", "2_4")
kssdata <- reshape(kssdata, direction = "long", , varying = c("kss2", "kss69"), idvar = c("subject", "sessionpair"), v.names = "kss")
kssdata$session <- 1
kssdata$session[kssdata$sessionpair == "1_3" & kssdata$time == 2] <- 3
kssdata$session[kssdata$sessionpair == "2_4" & kssdata$time == 1] <- 2
kssdata$session[kssdata$sessionpair == "2_4" & kssdata$time == 2] <- 4
kssdata <- kssdata[, c("subject", "session", "kss")]
kssdata$subject <- as.integer(kssdata$subject)

data_glob  <- merge(data_glob, kssdata, by = c("subject", "session"))

# Read sleep data
sleepdata <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/SleepData_160428.csv")
sleepdata <- sleepdata[sleepdata$Subject %in% subjects$subject, ]
unique(sleepdata$Subject)

data_glob$occasion <- 1
data_glob$occasion[data_glob$session == 2 | data_glob$session == 4] <- 2

data_glob <- merge(data_glob, sleepdata, by.x = c("subject", "occasion"), by.y = c("Subject", "Session"), all = T)

# Change reference levels for modelling
data_glob$AgeGroup <- relevel(data_glob$AgeGroup, ref = "Young")
data_glob$condition <- as.factor(data_glob$condition)
data_glob$condition <- relevel(data_glob$condition, ref = "fullsleep")

data_glob$run <- "first"
data_glob$run[data_glob$session == 3 | data_glob$session == 4] <- "second"
data_glob$run <- as.factor(data_glob$run)
data_glob$run <- relevel(data_glob$run, ref = "first")

#######################

# Main analyses
require(nlme)
require(effects)
require(RColorBrewer)
cols <- brewer.pal(n = 3, name = "Dark2")

# Full model, global signal amplitude
lm1 <- lme(globalsignal_logsd ~ condition * AgeGroup + FD, data = data_glob, random = ~1|ID)
summary(lm1)
intervals(lm1)
plot(effect("condition*AgeGroup", lm1))

pdf("GS.pdf", height = 6, width = 6) 
par(mar = c(4, 5, 1, 2))
plot(1, frame.plot = F, xlim = c(0, 1), ylim = c(2.3, 3.1), xlab = "", ylab = "Global signal amplitude (ln sd)", xaxt = "n", type = "n")
axis(1, at = c(0.05, 0.95), labels = c("Full sleep", "Sleep deprived"))
lines(x = c(0, 0.9), y = effect("condition*AgeGroup", lm1)$fit[1:2], pch = 16, col = cols[3], type = "b", lwd = 1.5)
lines(x = c(0.1, 1), y = effect("condition*AgeGroup", lm1)$fit[3:4], pch = 16, col = cols[2], type = "b", lwd = 1.5)
lines(x = c(0, 0), y = c(effect("condition*AgeGroup", lm1)$lower[1], effect("condition*AgeGroup", lm1)$upper[1]), col = cols[3], lwd = 1.5)
lines(x = c(0.9, 0.9), y = c(effect("condition*AgeGroup", lm1)$lower[2], effect("condition*AgeGroup", lm1)$upper[2]), col = cols[3], lwd = 1.5)
lines(x = c(0.1, 0.1), y = c(effect("condition*AgeGroup", lm1)$lower[3], effect("condition*AgeGroup", lm1)$upper[3]), col = cols[2], lwd = 1.5)
lines(x = c(1, 1), y = c(effect("condition*AgeGroup", lm1)$lower[4], effect("condition*AgeGroup", lm1)$upper[4]), col = cols[2], lwd = 1.5)
legend("topleft", lty = 1, lwd = 1.5, pch = 16, col = cols[3:2], legend = c("Younger", "Older"), bty = "n")
dev.off()

#######################

# Analyses of covariates

# KSS
lm2 <- lme(globalsignal_logsd ~ kss * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID)
summary(lm2)
intervals(lm2)
plot(effect("kss*AgeGroup", lm2))

lm3 <- lme(globalsignal_logsd ~ kss * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID)
summary(lm3)
intervals(lm3)
plot(effect("kss*AgeGroup", lm3))

lm4 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * kss + FD, data = subset(data_glob), random = ~1|ID)
summary(lm4)
intervals(lm4)
plot(effect("condition*kss", lm4))
plot(effect("AgeGroup*kss", lm4))

# Sleep measures
# Total sleep time
lm5 <- lme(globalsignal_logsd ~ TST * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm5)
intervals(lm5)
plot(effect("TST*AgeGroup", lm5))

lm6 <- lme(globalsignal_logsd ~ TST * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm6)
intervals(lm6)
plot(effect("TST*AgeGroup", lm6))

lm7 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * TST + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm7)
intervals(lm7)
plot(effect("condition*TST", lm7))
plot(effect("AgeGroup*TST", lm7))

# REM
lm8 <- lme(globalsignal_logsd ~ REM_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm8)
intervals(lm8)
plot(effect("REM_.*AgeGroup", lm8))

lm9 <- lme(globalsignal_logsd ~ REM_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm9)
intervals(lm9)
plot(effect("REM_.*AgeGroup", lm9))

lm10 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * REM_. + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm10)
intervals(lm10)
plot(effect("condition*REM_.", lm10))
plot(effect("AgeGroup*REM_.", lm10))

# Stage 1 sleep
lm11 <- lme(globalsignal_logsd ~ St1_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm11)
intervals(lm11)
plot(effect("St1_.*AgeGroup", lm11))

lm12 <- lme(globalsignal_logsd ~ St1_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm12)
intervals(lm12)
plot(effect("St1_.*AgeGroup", lm12))

lm13 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * St1_. + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm13)
intervals(lm13)
plot(effect("condition*St1_.", lm13))
plot(effect("AgeGroup*St1_.", lm13))

# Stage 2 sleep
lm14 <- lme(globalsignal_logsd ~ St2_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm14)
intervals(lm14)
plot(effect("St2_.*AgeGroup", lm14))

lm15 <- lme(globalsignal_logsd ~ St2_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm15)
intervals(lm15)
plot(effect("St2_.*AgeGroup", lm15))

lm16 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * St2_. + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm16)
intervals(lm16)
plot(effect("condition*St2_.", lm16))
plot(effect("AgeGroup*St2_.", lm16))

# Stage 3 sleep (SWS)
lm17 <- lme(globalsignal_logsd ~ St3_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm17)
intervals(lm17)
plot(effect("St3_.*AgeGroup", lm17))

lm18 <- lme(globalsignal_logsd ~ St3_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm18)
intervals(lm18)
plot(effect("St3_.*AgeGroup", lm18))

lm19 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * St3_. + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm19)
intervals(lm19)
plot(effect("condition*St3_.", lm19))
plot(effect("AgeGroup*St3_.", lm19))

# Stage changes
lm20 <- lme(globalsignal_logsd ~ NOSST * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm20)
intervals(lm20)
plot(effect("NOSST*AgeGroup", lm20))

lm21 <- lme(globalsignal_logsd ~ NOSST * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm21)
intervals(lm21)
plot(effect("NOSST*AgeGroup", lm21))

lm22 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * NOSST + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm22)
intervals(lm22)
plot(effect("condition*NOSST", lm22))
plot(effect("AgeGroup*NOSST", lm22))

# Delta power

# Number of awakenings
lm26 <- lme(globalsignal_logsd ~ Aw_index * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm26)
intervals(lm26)
plot(effect("Aw_index*AgeGroup", lm26))

lm27 <- lme(globalsignal_logsd ~ Aw_index * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm27)
intervals(lm27)
plot(effect("Aw_index*AgeGroup", lm27))

lm28 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * Aw_index + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm28)
intervals(lm28)
plot(effect("condition*Aw_index", lm28))
plot(effect("AgeGroup*Aw_index", lm28))

# Sleep efficiency
lm29 <- lme(globalsignal_logsd ~ SlEff_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm29)
intervals(lm29)
plot(effect("SlEff_.*AgeGroup", lm29))

lm30 <- lme(globalsignal_logsd ~ SlEff_. * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm30)
intervals(lm30)
plot(effect("SlEff_.*AgeGroup", lm30))

lm31 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * SlEff_. + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm31)
intervals(lm31)
plot(effect("condition*SlEff_.", lm31))
plot(effect("AgeGroup*SlEff_.", lm31))

# WTSP
lm32 <- lme(globalsignal_logsd ~ WASO * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm32)
intervals(lm32)
plot(effect("WASO*AgeGroup", lm32))

lm33 <- lme(globalsignal_logsd ~ WASO * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm33)
intervals(lm33)
plot(effect("WASO*AgeGroup", lm33))

lm34 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * WASO + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm34)
intervals(lm34)
plot(effect("condition*WASO", lm34))
plot(effect("AgeGroup*WASO", lm34))

# ISI
lm35 <- lme(globalsignal_logsd ~ ISI * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm35)
intervals(lm35)
plot(effect("ISI*AgeGroup", lm35))

lm36 <- lme(globalsignal_logsd ~ ISI * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm36)
intervals(lm36)
plot(effect("ISI*AgeGroup", lm36))

lm37 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * ISI + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm37)
intervals(lm37)
plot(effect("condition*ISI", lm37))
plot(effect("AgeGroup*ISI", lm37))


# ESS
lm38 <- lme(globalsignal_logsd ~ ESS * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm38)
intervals(lm38)
plot(effect("ESS*AgeGroup", lm38))

lm39 <- lme(globalsignal_logsd ~ ESS * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm39)
intervals(lm39)
plot(effect("ESS*AgeGroup", lm39))

lm40 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * ESS + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm40)
intervals(lm40)
plot(effect("condition*ESS", lm40))
plot(effect("AgeGroup*ESS", lm40))


# KSQ sleep quality
lm41 <- lme(globalsignal_logsd ~ KSQ_SleepQualityIndex * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm41)
intervals(lm41)
plot(effect("KSQ_SleepQualityIndex*AgeGroup", lm41))

lm42 <- lme(globalsignal_logsd ~ KSQ_SleepQualityIndex * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm42)
intervals(lm42)
plot(effect("KSQ_SleepQualityIndex*AgeGroup", lm42))

lm43 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * KSQ_SleepQualityIndex + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm43)
intervals(lm43)
plot(effect("condition*KSQ_SleepQualityIndex", lm43))
plot(effect("AgeGroup*KSQ_SleepQualityIndex", lm43))

# Post-hoc: investgate correlation between sleep efficiency and WTSP
plot(WASO ~ SlEff_., data = data_glob)
abline(lm(WASO ~ SlEff_., data = data_glob), col = "red")
lm_a <- lme(WASO ~ SlEff_., data = data_glob[data_glob$session %in% c(1,2), ], random = ~1|ID, na.action = na.omit)
cor.test(data_glob$WASO[data_glob$session %in% c(1,2) & data_glob$condition == "fullsleep"], data_glob$SlEff_.[data_glob$session %in% c(1,2) & data_glob$condition == "fullsleep"])
cor.test(data_glob$WASO[data_glob$session %in% c(1,2) & data_glob$condition == "sleepdeprived"], data_glob$SlEff_.[data_glob$session %in% c(1,2) & data_glob$condition == "sleepdeprived"])
