# Script to analyse global signal amplitude

# Require packages
require(xtable)
require(nlme)
require(effects)
require(RColorBrewer)
cols <- brewer.pal(n = 3, name = "Dark2")

# Read files
# The files contain nuisance regressors, including motion and total signal from GM, WM, and CSF, generated by DPARSFA
files_S1 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/FunImgARWSDFCovs", pattern = c("Covariables", ".txt"))
files_S1 <- files_S1[(seq(2, 106, 2))] # Workaround to get only .txt files
covs_S1 <- list()
for (i in 1:length(files_S1)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/FunImgARWSDFCovs/", files_S1[i], sep = ""))
  covs_S1[[i]] <- data$V10
}

files_S2 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S2_FunImgARWSDFCovs", pattern = c("Covariables", ".txt"))
files_S2 <- files_S2[(seq(2, 106, 2))] # Workaround to get only .txt files
covs_S2 <- list()
for (i in 1:length(files_S2)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S2_FunImgARWSDFCovs/", files_S2[i], sep = ""))
  covs_S2[[i]] <- data$V10
}

files_S3 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S3_FunImgARWSDFCovs", pattern = c("Covariables", ".txt"))
files_S3 <- files_S3[(seq(2, 106, 2))] # Workaround to get only .txt files
covs_S3 <- list()
for (i in 1:length(files_S3)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S3_FunImgARWSDFCovs/", files_S3[i], sep = ""))
  covs_S3[[i]] <- data$V10
}

files_S4 <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S4_FunImgARWSDFCovs", pattern = c("Covariables", ".txt"))
files_S4 <- files_S4[(seq(2, 106, 2))] # Workaround to get only .txt files
covs_S4 <- list()
for (i in 1:length(files_S4)){
  data <- read.table(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting State/Covs_151110b_160407/S4_FunImgARWSDFCovs/", files_S4[i], sep = ""))
  covs_S4[[i]] <- data$V10
}

########################

# Calculate global signal amplitude and other measures and put in data frame
fun_rms <- function(x) sqrt(mean(x^2))

data_glob <- data.frame(
  ID = rep(1:53, 4),
  session = c(rep(1, 53), rep(2, 53), rep(3, 53), rep(4, 53)),
  globalsignal = c(unlist(lapply(covs_S1, mean)), unlist(lapply(covs_S2, mean)), unlist(lapply(covs_S3, mean)), unlist(lapply(covs_S4, mean))),
  globalsignal_rms = c(unlist(lapply(covs_S1, fun_rms)), unlist(lapply(covs_S2, fun_rms)), unlist(lapply(covs_S3, fun_rms)), unlist(lapply(covs_S4, fun_rms))),
  globalsignal_sd = c(unlist(lapply(covs_S1, sd)), unlist(lapply(covs_S2, sd)), unlist(lapply(covs_S3, sd)), unlist(lapply(covs_S4, sd)))
)

hist(data_glob$globalsignal)
hist(data_glob$globalsignal_rms)
hist(data_glob$globalsignal_sd)
hist(log(data_glob$globalsignal_sd))

data_glob$globalsignal_logsd <- log(data_glob$globalsignal_sd) # Log transform to achieve a more normal distribution

########################

# Read data files for randomisation list etc, make final data frame
subjects <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/Subjects_RestingState_151110.csv")
demdata <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/150215_Demographic.csv")
demdata <- merge(subjects, demdata, by.x = "subject", by.y = "Subject")
randlist <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/RandomisationList_140804.csv")
demdata <- merge(demdata, randlist, by.x = "subject", by.y = "Subject")
FDdata <- read.table("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Resting state/RealignParameter_RestingState_151001/n_excluded.txt", header = T) # Framewise displacement, data say how many volumes had FD > 0.5 and were interpolated
FDdata <- reshape(FDdata, direction = "long", varying = c("S1", "S2", "S3", "S4"), idvar = "subject", v.names = "FD")
FDdata <- FDdata[with(FDdata, order(subject, time)), ]

data_glob <- merge(data_glob, subjects, by = "ID")
data_glob <- merge(data_glob, randlist[, 1:2], by.x = "subject", by.y = "Subject")

data_glob$condition <- "fullsleep"
data_glob$condition[data_glob$session == 1 & data_glob$Sl_cond == 1] <- "sleepdeprived"
data_glob$condition[data_glob$session == 3 & data_glob$Sl_cond == 1] <- "sleepdeprived"
data_glob$condition[data_glob$session == 2 & data_glob$Sl_cond == 2] <- "sleepdeprived"
data_glob$condition[data_glob$session == 4 & data_glob$Sl_cond == 2] <- "sleepdeprived"

data_glob <- merge(data_glob, demdata)
data_glob <- merge(data_glob, FDdata, by.x = c("subject", "session"), by.y = c("subject", "time"))

# Read KSS data
KSSfolders <- list.files("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles")
KSSfolders <- data.frame(folder = KSSfolders, subject = as.integer(substring(KSSfolders, 1, 3)))
KSSfolders <- KSSfolders[KSSfolders$subject %in% subjects$subject, ]
kssdata <- data.frame(folder = NULL, kss2 = NULL, kss69 = NULL)
for (i in 1:length(KSSfolders$folder)){
  KSSratings2 <- read.delim(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles/", KSSfolders$folder[i], "/KSS_brief2.txt", sep = ""), skip = 1, header = F)
  KSSratings6_9 <- read.delim(paste("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/Presentation_logfiles/", KSSfolders$folder[i], "/KSS.txt", sep = ""), skip = 1, header = F)
  KSSratings6_9 <- mean(KSSratings6_9$V1)
  data <- data.frame(folder = KSSfolders$folder[i], kss2 = as.integer(KSSratings2), kss69 = KSSratings6_9)
  kssdata <- rbind(kssdata, data)
}

boxplot(kssdata$kss2, kssdata$kss69)
t.test(kssdata$kss2, kssdata$kss69)

kssdata$subject <- substring(kssdata$folder, 1, 3)
kssdata$sessionpair <- c("1_3", "2_4")
kssdata <- reshape(kssdata, direction = "long", , varying = c("kss2", "kss69"), idvar = c("subject", "sessionpair"), v.names = "kss")
kssdata$session <- 1
kssdata$session[kssdata$sessionpair == "1_3" & kssdata$time == 2] <- 3
kssdata$session[kssdata$sessionpair == "2_4" & kssdata$time == 1] <- 2
kssdata$session[kssdata$sessionpair == "2_4" & kssdata$time == 2] <- 4
kssdata <- kssdata[, c("subject", "session", "kss")]
kssdata$subject <- as.integer(kssdata$subject)

data_glob  <- merge(data_glob, kssdata, by = c("subject", "session"))

# Read sleep data
sleepdata <- read.delim("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/sb_wide_28_Jun_2016.txt")
sleepdata <- sleepdata[sleepdata$id %in% subjects$subject, ]
sleepdata_nsd <- sleepdata[, c(1:3192, 6384)]
sleepdata_sd <- sleepdata[, c(1, 3193:6384)]
sleepdata_nsd$condition <- "fullsleep"
sleepdata_sd$condition <- "sleepdeprived"

names(sleepdata_sd) <- names(sleepdata_nsd)
sleepdata2 <- rbind(sleepdata_nsd, sleepdata_sd)

data_glob$occasion <- 1
data_glob$occasion[data_glob$session == 2 | data_glob$session == 4] <- 2

data_glob <- merge(data_glob, sleepdata2, by.x = c("subject", "condition"), by.y = c("id", "condition"), all = T)

# Change reference levels for modelling
data_glob$AgeGroup <- relevel(data_glob$AgeGroup, ref = "Young")
data_glob$condition <- as.factor(data_glob$condition)
data_glob$condition <- relevel(data_glob$condition, ref = "fullsleep")

data_glob$run <- "first"
data_glob$run[data_glob$session == 3 | data_glob$session == 4] <- "second"
data_glob$run <- as.factor(data_glob$run)
data_glob$run <- relevel(data_glob$run, ref = "first")

#######################

# Main analyses

# Full model, global signal amplitude
lm1 <- lme(globalsignal_logsd ~ condition * AgeGroup + FD, data = data_glob, random = ~1|ID)
summary(lm1)
intervals(lm1)
plot(effect("condition*AgeGroup", lm1))

pdf("GS.pdf", height = 6, width = 6) 
par(mar = c(4, 5, 1, 2))
plot(1, frame.plot = F, xlim = c(0, 1), ylim = c(2.3, 3.1), xlab = "", ylab = "Global signal amplitude (ln sd)", xaxt = "n", type = "n")
axis(1, at = c(0.05, 0.95), labels = c("Full sleep", "Sleep deprived"))
lines(x = c(0, 0.9), y = effect("condition*AgeGroup", lm1)$fit[1:2], pch = 16, col = cols[3], type = "b", lwd = 1.5)
lines(x = c(0.1, 1), y = effect("condition*AgeGroup", lm1)$fit[3:4], pch = 16, col = cols[2], type = "b", lwd = 1.5)
lines(x = c(0, 0), y = c(effect("condition*AgeGroup", lm1)$lower[1], effect("condition*AgeGroup", lm1)$upper[1]), col = cols[3], lwd = 1.5)
lines(x = c(0.9, 0.9), y = c(effect("condition*AgeGroup", lm1)$lower[2], effect("condition*AgeGroup", lm1)$upper[2]), col = cols[3], lwd = 1.5)
lines(x = c(0.1, 0.1), y = c(effect("condition*AgeGroup", lm1)$lower[3], effect("condition*AgeGroup", lm1)$upper[3]), col = cols[2], lwd = 1.5)
lines(x = c(1, 1), y = c(effect("condition*AgeGroup", lm1)$lower[4], effect("condition*AgeGroup", lm1)$upper[4]), col = cols[2], lwd = 1.5)
legend("topleft", lty = 1, lwd = 1.5, pch = 16, col = cols[3:2], legend = c("Younger", "Older"), bty = "n")
dev.off()

#######################

# Analyses of covariates

# KSS
lm2 <- lme(globalsignal_logsd ~ kss * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID)
summary(lm2)
intervals(lm2)
plot(effect("kss*AgeGroup", lm2))

lm3 <- lme(globalsignal_logsd ~ kss * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID)
summary(lm3)
intervals(lm3)
plot(effect("kss*AgeGroup", lm3))

lm4 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * kss + FD, data = subset(data_glob), random = ~1|ID)
summary(lm4)
intervals(lm4)
plot(effect("condition*kss", lm4))
plot(effect("AgeGroup*kss", lm4))

# Sleep measures
# Total sleep time
lm5 <- lme(globalsignal_logsd ~ tst__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep" & data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm5)
intervals(lm5)
plot(effect("tst__00_nsd*AgeGroup", lm5))

lm6 <- lme(globalsignal_logsd ~ tst__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived" & data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm6)
intervals(lm6)
plot(effect("tst__00_nsd*AgeGroup", lm6))

lm7 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * tst__00_nsd + FD, data = subset(data_glob, data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm7)
intervals(lm7)
plot(effect("condition*tst__00_nsd", lm7))
plot(effect("AgeGroup*tst__00_nsd", lm7))

# REM
lm8 <- lme(globalsignal_logsd ~ rp___00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep" & data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm8)
intervals(lm8)
plot(effect("rp___00_nsd*AgeGroup", lm8))

lm9 <- lme(globalsignal_logsd ~ rp___00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived" & data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm9)
intervals(lm9)
plot(effect("rp___00_nsd*AgeGroup", lm9))

lm10 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * rp___00_nsd + FD, data = subset(data_glob, data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm10)
intervals(lm10)
plot(effect("condition*rp___00_nsd", lm10))
plot(effect("AgeGroup*rp___00_nsd", lm10))

# Stage 1 sleep
lm11 <- lme(globalsignal_logsd ~ n1p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm11)
intervals(lm11)
plot(effect("n1p__00_nsd*AgeGroup", lm11))

lm12 <- lme(globalsignal_logsd ~ n1p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm12)
intervals(lm12)
plot(effect("n1p__00_nsd*AgeGroup", lm12))

lm13 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * n1p__00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm13)
intervals(lm13)
plot(effect("condition*n1p__00_nsd", lm13))
plot(effect("AgeGroup*n1p__00_nsd", lm13))

# Stage 2 sleep
lm14 <- lme(globalsignal_logsd ~ n2p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm14)
intervals(lm14)
plot(effect("n2p__00_nsd*AgeGroup", lm14))

lm15 <- lme(globalsignal_logsd ~ n2p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm15)
intervals(lm15)
plot(effect("n2p__00_nsd*AgeGroup", lm15))

lm16 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * n2p__00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm16)
intervals(lm16)
plot(effect("condition*n2p__00_nsd", lm16))
plot(effect("AgeGroup*n2p__00_nsd", lm16))

# Stage 3 sleep (SWS)
lm17 <- lme(globalsignal_logsd ~ n3p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm17)
intervals(lm17)
plot(effect("n3p__00_nsd*AgeGroup", lm17))

lm18 <- lme(globalsignal_logsd ~ n3p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm18)
intervals(lm18)
plot(effect("n3p__00_nsd*AgeGroup", lm18))

lm19 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * n3p__00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm19)
intervals(lm19)
plot(effect("condition*n3p__00_nsd", lm19))
plot(effect("AgeGroup*n3p__00_nsd", lm19))

# Stage changes
lm20 <- lme(globalsignal_logsd ~ fstst00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm20)
intervals(lm20)
plot(effect("fstst00_nsd*AgeGroup", lm20))

lm21 <- lme(globalsignal_logsd ~ fstst00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm21)
intervals(lm21)
plot(effect("fstst00_nsd*AgeGroup", lm21))

lm22 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * fstst00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm22)
intervals(lm22)
plot(effect("condition*fstst00_nsd", lm22))
plot(effect("AgeGroup*fstst00_nsd", lm22))

# Delta power, absolute
lm23 <- lme(globalsignal_logsd ~ delta_t_l_n3_p25_m_use_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm23)
intervals(lm23)
plot(effect("delta_t_l_n3_p25_m_use_nsd*AgeGroup", lm23))

lm24 <- lme(globalsignal_logsd ~ delta_t_l_n3_p25_m_use_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm24)
intervals(lm24)
plot(effect("delta_t_l_n3_p25_m_use_nsd*AgeGroup", lm24))

lm25 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * delta_t_l_n3_p25_m_use_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm25)
intervals(lm25)
plot(effect("condition*delta_t_l_n3_p25_m_use_nsd", lm25))
plot(effect("AgeGroup*delta_t_l_n3_p25_m_use_nsd", lm25))

# Delta power, relative
lm23b <- lme(globalsignal_logsd ~ delta_r_l_n3_p25_m_use_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm23b)
intervals(lm23b)
plot(effect("delta_r_l_n3_p25_m_use_nsd*AgeGroup", lm23b))

lm24b <- lme(globalsignal_logsd ~ delta_r_l_n3_p25_m_use_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm24b)
intervals(lm24b)
plot(effect("delta_r_l_n3_p25_m_use_nsd*AgeGroup", lm24b))

lm25b <- lme(globalsignal_logsd ~ (condition + AgeGroup) * delta_r_l_n3_p25_m_use_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm25b)
intervals(lm25b)
plot(effect("condition*delta_r_l_n3_p25_m_use_nsd", lm25b))
plot(effect("AgeGroup*delta_r_l_n3_p25_m_use_nsd", lm25b))

# Number of awakenings
lm26 <- lme(globalsignal_logsd ~ fw___00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm26)
intervals(lm26)
plot(effect("fw___00_nsd*AgeGroup", lm26))

lm27 <- lme(globalsignal_logsd ~ fw___00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm27)
intervals(lm27)
plot(effect("fw___00_nsd*AgeGroup", lm27))

lm28 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * fw___00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm28)
intervals(lm28)
plot(effect("condition*fw___00_nsd", lm28))
plot(effect("AgeGroup*fw___00_nsd", lm28))

# Sleep efficiency
lm29 <- lme(globalsignal_logsd ~ eff__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm29)
intervals(lm29)
plot(effect("eff__00_nsd*AgeGroup", lm29))

lm30 <- lme(globalsignal_logsd ~ eff__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm30)
intervals(lm30)
plot(effect("eff__00_nsd*AgeGroup", lm30))

lm31 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * eff__00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm31)
intervals(lm31)
plot(effect("condition*eff__00_nsd", lm31))
plot(effect("AgeGroup*eff__00_nsd", lm31))

# WASO
lm32 <- lme(globalsignal_logsd ~ waso_00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm32)
intervals(lm32)
plot(effect("waso_00_nsd*AgeGroup", lm32))

lm33 <- lme(globalsignal_logsd ~ waso_00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm33)
intervals(lm33)
plot(effect("waso_00_nsd*AgeGroup", lm33))

lm34 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * waso_00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm34)
intervals(lm34)
plot(effect("condition*waso_00_nsd", lm34))
plot(effect("AgeGroup*waso_00_nsd", lm34))

# ISI
lm35 <- lme(globalsignal_logsd ~ ISI * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm35)
intervals(lm35)
plot(effect("ISI*AgeGroup", lm35))

lm36 <- lme(globalsignal_logsd ~ ISI * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm36)
intervals(lm36)
plot(effect("ISI*AgeGroup", lm36))

lm37 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * ISI + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm37)
intervals(lm37)
plot(effect("condition*ISI", lm37))
plot(effect("AgeGroup*ISI", lm37))


# ESS
lm38 <- lme(globalsignal_logsd ~ ESS * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm38)
intervals(lm38)
plot(effect("ESS*AgeGroup", lm38))

lm39 <- lme(globalsignal_logsd ~ ESS * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm39)
intervals(lm39)
plot(effect("ESS*AgeGroup", lm39))

lm40 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * ESS + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm40)
intervals(lm40)
plot(effect("condition*ESS", lm40))
plot(effect("AgeGroup*ESS", lm40))


# KSQ sleep quality
lm41 <- lme(globalsignal_logsd ~ KSQ_SleepQualityIndex * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm41)
intervals(lm41)
plot(effect("KSQ_SleepQualityIndex*AgeGroup", lm41))

lm42 <- lme(globalsignal_logsd ~ KSQ_SleepQualityIndex * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm42)
intervals(lm42)
plot(effect("KSQ_SleepQualityIndex*AgeGroup", lm42))

lm43 <- lme(globalsignal_logsd ~ (condition + AgeGroup) * KSQ_SleepQualityIndex + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm43)
intervals(lm43)
plot(effect("condition*KSQ_SleepQualityIndex", lm43))
plot(effect("AgeGroup*KSQ_SleepQualityIndex", lm43))


# Make table with results from above analyses
outtable <- data.frame(variable = "KSS main effect",
                       estimate_fullsleep = paste(round(intervals(lm2)$fixed[2, 2], 3), " [", round(intervals(lm2)$fixed[2, 1], 3), ", ", round(intervals(lm2)$fixed[2, 3], 3), "]", sep = ""), 
                       p_fullsleep = summary(lm2)$tTable[2, 5],
                       estimate_sleepdeprived = paste(round(intervals(lm3)$fixed[2, 2], 3), " [", round(intervals(lm3)$fixed[2, 1], 3), ", ", round(intervals(lm3)$fixed[2, 3], 3), "]", sep = ""), 
                       p_sleepdeprived = summary(lm3)$tTable[2, 5],
                       estimate_bothconditions = paste(round(intervals(lm4)$fixed[4, 2], 3), " [", round(intervals(lm4)$fixed[4, 1], 3), ", ", round(intervals(lm4)$fixed[4, 3], 3), "]", sep = ""), 
                       p_bothconditions = summary(lm4)$tTable[4, 5])
outtable <- rbind(outtable, data.frame(variable = "KSS-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm2)$fixed[5, 2], 3), " [", round(intervals(lm2)$fixed[5, 1], 3), ", ", round(intervals(lm2)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm2)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm3)$fixed[5, 2], 3), " [", round(intervals(lm3)$fixed[5, 1], 3), ", ", round(intervals(lm3)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm3)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm4)$fixed[7, 2], 3), " [", round(intervals(lm4)$fixed[7, 1], 3), ", ", round(intervals(lm4)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm4)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "TST main effect",
                                        estimate_fullsleep = paste(round(intervals(lm5)$fixed[2, 2], 3), " [", round(intervals(lm5)$fixed[2, 1], 3), ", ", round(intervals(lm5)$fixed[2, 3], 3), "]", sep = ""), 
                                        p_fullsleep = summary(lm5)$tTable[2, 5],
                                        estimate_sleepdeprived = paste(round(intervals(lm6)$fixed[2, 2], 3), " [", round(intervals(lm6)$fixed[2, 1], 3), ", ", round(intervals(lm6)$fixed[2, 3], 3), "]", sep = ""), 
                                        p_sleepdeprived = summary(lm6)$tTable[2, 5],
                                        estimate_bothconditions = paste(round(intervals(lm7)$fixed[4, 2], 3), " [", round(intervals(lm7)$fixed[4, 1], 3), ", ", round(intervals(lm7)$fixed[4, 3], 3), "]", sep = ""), 
                                        p_bothconditions = summary(lm7)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "TST-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm5)$fixed[5, 2], 3), " [", round(intervals(lm5)$fixed[5, 1], 3), ", ", round(intervals(lm5)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm5)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm6)$fixed[5, 2], 3), " [", round(intervals(lm6)$fixed[5, 1], 3), ", ", round(intervals(lm6)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm6)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm7)$fixed[7, 2], 3), " [", round(intervals(lm7)$fixed[7, 1], 3), ", ", round(intervals(lm7)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm7)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "REM main effect",
                                       estimate_fullsleep = paste(round(intervals(lm8)$fixed[2, 2], 3), " [", round(intervals(lm8)$fixed[2, 1], 3), ", ", round(intervals(lm8)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm8)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm9)$fixed[2, 2], 3), " [", round(intervals(lm9)$fixed[2, 1], 3), ", ", round(intervals(lm9)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm9)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm10)$fixed[4, 2], 3), " [", round(intervals(lm10)$fixed[4, 1], 3), ", ", round(intervals(lm10)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm10)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "REM-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm8)$fixed[5, 2], 3), " [", round(intervals(lm8)$fixed[5, 1], 3), ", ", round(intervals(lm8)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm8)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm9)$fixed[5, 2], 3), " [", round(intervals(lm9)$fixed[5, 1], 3), ", ", round(intervals(lm9)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm9)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm10)$fixed[7, 2], 3), " [", round(intervals(lm10)$fixed[7, 1], 3), ", ", round(intervals(lm10)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm10)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "Stage 1 main effect",
                                       estimate_fullsleep = paste(round(intervals(lm11)$fixed[2, 2], 3), " [", round(intervals(lm11)$fixed[2, 1], 3), ", ", round(intervals(lm11)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm11)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm12)$fixed[2, 2], 3), " [", round(intervals(lm12)$fixed[2, 1], 3), ", ", round(intervals(lm12)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm12)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm13)$fixed[4, 2], 3), " [", round(intervals(lm13)$fixed[4, 1], 3), ", ", round(intervals(lm13)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm13)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Stage 1-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm11)$fixed[5, 2], 3), " [", round(intervals(lm11)$fixed[5, 1], 3), ", ", round(intervals(lm11)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm11)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm12)$fixed[5, 2], 3), " [", round(intervals(lm12)$fixed[5, 1], 3), ", ", round(intervals(lm12)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm12)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm13)$fixed[7, 2], 3), " [", round(intervals(lm13)$fixed[7, 1], 3), ", ", round(intervals(lm13)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm13)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "Stage 2 main effect",
                                       estimate_fullsleep = paste(round(intervals(lm14)$fixed[2, 2], 3), " [", round(intervals(lm14)$fixed[2, 1], 3), ", ", round(intervals(lm14)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm14)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm15)$fixed[2, 2], 3), " [", round(intervals(lm15)$fixed[2, 1], 3), ", ", round(intervals(lm15)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm15)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm16)$fixed[4, 2], 3), " [", round(intervals(lm16)$fixed[4, 1], 3), ", ", round(intervals(lm16)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm16)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Stage 2-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm14)$fixed[5, 2], 3), " [", round(intervals(lm14)$fixed[5, 1], 3), ", ", round(intervals(lm14)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm14)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm15)$fixed[5, 2], 3), " [", round(intervals(lm15)$fixed[5, 1], 3), ", ", round(intervals(lm15)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm15)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm16)$fixed[7, 2], 3), " [", round(intervals(lm16)$fixed[7, 1], 3), ", ", round(intervals(lm16)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm16)$tTable[7, 5]))


outtable <- rbind(outtable, data.frame(variable = "Stage 3 main effect",
                                       estimate_fullsleep = paste(round(intervals(lm23)$fixed[2, 2], 3), " [", round(intervals(lm23)$fixed[2, 1], 3), ", ", round(intervals(lm23)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm18)$fixed[2, 2], 3), " [", round(intervals(lm18)$fixed[2, 1], 3), ", ", round(intervals(lm18)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm18)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm19)$fixed[4, 2], 3), " [", round(intervals(lm19)$fixed[4, 1], 3), ", ", round(intervals(lm19)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm19)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Stage 3-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm23)$fixed[5, 2], 3), " [", round(intervals(lm23)$fixed[5, 1], 3), ", ", round(intervals(lm23)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm18)$fixed[5, 2], 3), " [", round(intervals(lm18)$fixed[5, 1], 3), ", ", round(intervals(lm18)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm18)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm19)$fixed[7, 2], 3), " [", round(intervals(lm19)$fixed[7, 1], 3), ", ", round(intervals(lm19)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm19)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "Stage changes main effect",
                                       estimate_fullsleep = paste(round(intervals(lm20)$fixed[2, 2], 3), " [", round(intervals(lm20)$fixed[2, 1], 3), ", ", round(intervals(lm20)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm20)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm21)$fixed[2, 2], 3), " [", round(intervals(lm21)$fixed[2, 1], 3), ", ", round(intervals(lm21)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm21)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm22)$fixed[4, 2], 3), " [", round(intervals(lm22)$fixed[4, 1], 3), ", ", round(intervals(lm22)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm22)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Stage changes interaction",
                                       estimate_fullsleep = paste(round(intervals(lm20)$fixed[5, 2], 3), " [", round(intervals(lm20)$fixed[5, 1], 3), ", ", round(intervals(lm20)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm20)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm21)$fixed[5, 2], 3), " [", round(intervals(lm21)$fixed[5, 1], 3), ", ", round(intervals(lm21)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm21)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm22)$fixed[7, 2], 3), " [", round(intervals(lm22)$fixed[7, 1], 3), ", ", round(intervals(lm22)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm22)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "Delta power (absolute) main effect",
                                       estimate_fullsleep = paste(round(intervals(lm23)$fixed[2, 2], 3), " [", round(intervals(lm23)$fixed[2, 1], 3), ", ", round(intervals(lm23)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm24)$fixed[2, 2], 3), " [", round(intervals(lm24)$fixed[2, 1], 3), ", ", round(intervals(lm24)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm24)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm25)$fixed[4, 2], 3), " [", round(intervals(lm25)$fixed[4, 1], 3), ", ", round(intervals(lm25)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm25)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Delta power (absolute) interaction",
                                       estimate_fullsleep = paste(round(intervals(lm23)$fixed[5, 2], 3), " [", round(intervals(lm23)$fixed[5, 1], 3), ", ", round(intervals(lm23)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm24)$fixed[5, 2], 3), " [", round(intervals(lm24)$fixed[5, 1], 3), ", ", round(intervals(lm24)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm24)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm25)$fixed[7, 2], 3), " [", round(intervals(lm25)$fixed[7, 1], 3), ", ", round(intervals(lm25)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm25)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "Delta power (relative) main effect",
                                       estimate_fullsleep = paste(round(intervals(lm23b)$fixed[2, 2], 3), " [", round(intervals(lm23b)$fixed[2, 1], 3), ", ", round(intervals(lm23b)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23b)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm24b)$fixed[2, 2], 3), " [", round(intervals(lm24b)$fixed[2, 1], 3), ", ", round(intervals(lm24b)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm24b)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm25b)$fixed[4, 2], 3), " [", round(intervals(lm25b)$fixed[4, 1], 3), ", ", round(intervals(lm25b)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm25b)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Delta power (relative) interaction",
                                       estimate_fullsleep = paste(round(intervals(lm23b)$fixed[5, 2], 3), " [", round(intervals(lm23b)$fixed[5, 1], 3), ", ", round(intervals(lm23b)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23b)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm24b)$fixed[5, 2], 3), " [", round(intervals(lm24b)$fixed[5, 1], 3), ", ", round(intervals(lm24b)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm24b)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm25b)$fixed[7, 2], 3), " [", round(intervals(lm25b)$fixed[7, 1], 3), ", ", round(intervals(lm25b)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm25b)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "Number of awakenings main effect",
                                       estimate_fullsleep = paste(round(intervals(lm26)$fixed[2, 2], 3), " [", round(intervals(lm26)$fixed[2, 1], 3), ", ", round(intervals(lm26)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm26)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm27)$fixed[2, 2], 3), " [", round(intervals(lm27)$fixed[2, 1], 3), ", ", round(intervals(lm27)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm27)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm28)$fixed[4, 2], 3), " [", round(intervals(lm28)$fixed[4, 1], 3), ", ", round(intervals(lm28)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm28)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Number of awakenings interaction",
                                       estimate_fullsleep = paste(round(intervals(lm26)$fixed[5, 2], 3), " [", round(intervals(lm26)$fixed[5, 1], 3), ", ", round(intervals(lm26)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm26)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm27)$fixed[5, 2], 3), " [", round(intervals(lm27)$fixed[5, 1], 3), ", ", round(intervals(lm27)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm27)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm28)$fixed[7, 2], 3), " [", round(intervals(lm28)$fixed[7, 1], 3), ", ", round(intervals(lm28)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm28)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "Sleep efficiency main effect",
                                       estimate_fullsleep = paste(round(intervals(lm29)$fixed[2, 2], 3), " [", round(intervals(lm29)$fixed[2, 1], 3), ", ", round(intervals(lm29)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm29)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm30)$fixed[2, 2], 3), " [", round(intervals(lm30)$fixed[2, 1], 3), ", ", round(intervals(lm30)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm30)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm31)$fixed[4, 2], 3), " [", round(intervals(lm31)$fixed[4, 1], 3), ", ", round(intervals(lm31)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm31)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Sleep efficiency interaction",
                                       estimate_fullsleep = paste(round(intervals(lm29)$fixed[5, 2], 3), " [", round(intervals(lm29)$fixed[5, 1], 3), ", ", round(intervals(lm29)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm29)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm30)$fixed[5, 2], 3), " [", round(intervals(lm30)$fixed[5, 1], 3), ", ", round(intervals(lm30)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm30)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm31)$fixed[7, 2], 3), " [", round(intervals(lm31)$fixed[7, 1], 3), ", ", round(intervals(lm31)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm31)$tTable[7, 5]))

outtable <- rbind(outtable, data.frame(variable = "Wake after sleep onset main effect",
                                       estimate_fullsleep = paste(round(intervals(lm32)$fixed[2, 2], 3), " [", round(intervals(lm32)$fixed[2, 1], 3), ", ", round(intervals(lm32)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm32)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm33)$fixed[2, 2], 3), " [", round(intervals(lm33)$fixed[2, 1], 3), ", ", round(intervals(lm33)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm33)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm34)$fixed[4, 2], 3), " [", round(intervals(lm34)$fixed[4, 1], 3), ", ", round(intervals(lm34)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm34)$tTable[4, 5]))
outtable <- rbind(outtable, data.frame(variable = "Wake after sleep onset interaction",
                                       estimate_fullsleep = paste(round(intervals(lm32)$fixed[5, 2], 3), " [", round(intervals(lm32)$fixed[5, 1], 3), ", ", round(intervals(lm32)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm32)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm33)$fixed[5, 2], 3), " [", round(intervals(lm33)$fixed[5, 1], 3), ", ", round(intervals(lm33)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm33)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm34)$fixed[7, 2], 3), " [", round(intervals(lm34)$fixed[7, 1], 3), ", ", round(intervals(lm34)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm34)$tTable[7, 5]))



outtable$p_fullsleep[outtable$p_fullsleep > 0.01] <- round(outtable$p_fullsleep[outtable$p_fullsleep > 0.01], 2)
outtable$p_sleepdeprived[outtable$p_sleepdeprived > 0.01] <- round(outtable$p_sleepdeprived[outtable$p_sleepdeprived > 0.01], 2)
outtable$p_bothconditions[outtable$p_bothconditions > 0.001] <- round(outtable$p_bothconditions[outtable$p_bothconditions > 0.001], 3)

print.xtable(xtable(outtable), include.rownames = F, type="html", file="GS_covariates.html")

# Post-hoc: investgate correlation between sleep efficiency and WTSP
plot(WASO ~ SlEff_., data = data_glob)
abline(lm(WASO ~ SlEff_., data = data_glob), col = "red")
lm_a <- lme(WASO ~ SlEff_., data = data_glob[data_glob$session %in% c(1,2), ], random = ~1|ID, na.action = na.omit)
cor.test(data_glob$WASO[data_glob$session %in% c(1,2) & data_glob$condition == "fullsleep"], data_glob$SlEff_.[data_glob$session %in% c(1,2) & data_glob$condition == "fullsleep"])
cor.test(data_glob$WASO[data_glob$session %in% c(1,2) & data_glob$condition == "sleepdeprived"], data_glob$SlEff_.[data_glob$session %in% c(1,2) & data_glob$condition == "sleepdeprived"])

# Post-hoc: Investigate difference between WASO and sleep efficiency variables in Paolo's scoring and the SIESTA data
manualsleepdata <- read.csv2("C:/Users/Gustav Nilsonne/Box Sync/Sleepy Brain/Datafiles/SleepData_160428.csv")

data_glob2 <- merge(data_glob, manualsleepdata, by.x = c("subject", "session"), by.y = c("Subject", "Session"))

plot(data_glob2$eff__00_nsd[data_glob2$condition == "fullsleep"] ~ data_glob2$SlEff_.[data_glob2$condition == "fullsleep"],
     frame.plot = F, xlim = c(55, 100), ylim = c(55, 100), xlab = "Manual", ylab = "Siesta", main = "Sleep efficiency, %")
lines(x = c(55, 100), y = c(55, 100), col = "gray")
points(data_glob2$eff__00_nsd[data_glob2$condition == "sleepdeprived"] ~ data_glob2$SlEff_.[data_glob2$condition == "sleepdeprived"], pch = 19)
legend("bottomright", pch = c(1, 16), legend = c("Full sleep", "Sleep Deprived"))

plot(data_glob2$waso_00_nsd[data_glob2$condition == "fullsleep"] ~ data_glob2$WASO[data_glob2$condition == "fullsleep"],
     frame.plot = F, xlim = c(0, 100), ylim = c(0, 100), xlab = "Manual", ylab = "Siesta", main = "WASO, minutes")
lines(x = c(0, 100), y = c(0, 100), col = "gray")
points(data_glob2$waso_00_nsd[data_glob2$condition == "sleepdeprived"] ~ data_glob2$WASO[data_glob2$condition == "sleepdeprived"], pch = 19)
legend("bottomright", pch = c(1, 16), legend = c("Full sleep", "Sleep Deprived"))



#######################

# Now do the same with the global signal itself
# Full model, global signal 
lm1 <- lme(globalsignal ~ condition * AgeGroup + FD, data = data_glob, random = ~1|ID)
summary(lm1)
intervals(lm1)
plot(effect("condition*AgeGroup", lm1))

pdf("GS1.pdf", height = 6, width = 6) 
par(mar = c(4, 5, 1, 2))
plot(1, frame.plot = F, xlim = c(0, 1), ylim = c(4100, 4400), xlab = "", ylab = "Global signal", xaxt = "n", type = "n")
axis(1, at = c(0.05, 0.95), labels = c("Full sleep", "Sleep deprived"))
lines(x = c(0, 0.9), y = effect("condition*AgeGroup", lm1)$fit[1:2], pch = 16, col = cols[3], type = "b", lwd = 1.5)
lines(x = c(0.1, 1), y = effect("condition*AgeGroup", lm1)$fit[3:4], pch = 16, col = cols[2], type = "b", lwd = 1.5)
lines(x = c(0, 0), y = c(effect("condition*AgeGroup", lm1)$lower[1], effect("condition*AgeGroup", lm1)$upper[1]), col = cols[3], lwd = 1.5)
lines(x = c(0.9, 0.9), y = c(effect("condition*AgeGroup", lm1)$lower[2], effect("condition*AgeGroup", lm1)$upper[2]), col = cols[3], lwd = 1.5)
lines(x = c(0.1, 0.1), y = c(effect("condition*AgeGroup", lm1)$lower[3], effect("condition*AgeGroup", lm1)$upper[3]), col = cols[2], lwd = 1.5)
lines(x = c(1, 1), y = c(effect("condition*AgeGroup", lm1)$lower[4], effect("condition*AgeGroup", lm1)$upper[4]), col = cols[2], lwd = 1.5)
legend("topleft", lty = 1, lwd = 1.5, pch = 16, col = cols[3:2], legend = c("Younger", "Older"), bty = "n")
dev.off()

#######################

# Analyses of covariates

# KSS
lm2 <- lme(globalsignal ~ kss * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID)
summary(lm2)
intervals(lm2)
plot(effect("kss*AgeGroup", lm2))

lm3 <- lme(globalsignal ~ kss * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID)
summary(lm3)
intervals(lm3)
plot(effect("kss*AgeGroup", lm3))

lm4 <- lme(globalsignal ~ (condition + AgeGroup) * kss + FD, data = subset(data_glob), random = ~1|ID)
summary(lm4)
intervals(lm4)
plot(effect("condition*kss", lm4))
plot(effect("AgeGroup*kss", lm4))

# Sleep measures
# Total sleep time
lm5 <- lme(globalsignal ~ tst__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep" & data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm5)
intervals(lm5)
plot(effect("tst__00_nsd*AgeGroup", lm5))

lm6 <- lme(globalsignal ~ tst__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived" & data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm6)
intervals(lm6)
plot(effect("tst__00_nsd*AgeGroup", lm6))

lm7 <- lme(globalsignal ~ (condition + AgeGroup) * tst__00_nsd + FD, data = subset(data_glob, data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm7)
intervals(lm7)
plot(effect("condition*tst__00_nsd", lm7))
plot(effect("AgeGroup*tst__00_nsd", lm7))

# REM
lm8 <- lme(globalsignal ~ rp___00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep" & data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm8)
intervals(lm8)
plot(effect("rp___00_nsd*AgeGroup", lm8))

lm9 <- lme(globalsignal ~ rp___00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived" & data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm9)
intervals(lm9)
plot(effect("rp___00_nsd*AgeGroup", lm9))

lm10 <- lme(globalsignal ~ (condition + AgeGroup) * rp___00_nsd + FD, data = subset(data_glob, data_glob$device_nsd == "Embla"), random = ~1|ID, na.action = na.omit)
summary(lm10)
intervals(lm10)
plot(effect("condition*rp___00_nsd", lm10))
plot(effect("AgeGroup*rp___00_nsd", lm10))

# Stage 1 sleep
lm11 <- lme(globalsignal ~ n1p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm11)
intervals(lm11)
plot(effect("n1p__00_nsd*AgeGroup", lm11))

lm12 <- lme(globalsignal ~ n1p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm12)
intervals(lm12)
plot(effect("n1p__00_nsd*AgeGroup", lm12))

lm13 <- lme(globalsignal ~ (condition + AgeGroup) * n1p__00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm13)
intervals(lm13)
plot(effect("condition*n1p__00_nsd", lm13))
plot(effect("AgeGroup*n1p__00_nsd", lm13))

# Stage 2 sleep
lm14 <- lme(globalsignal ~ n2p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm14)
intervals(lm14)
plot(effect("n2p__00_nsd*AgeGroup", lm14))

lm15 <- lme(globalsignal ~ n2p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm15)
intervals(lm15)
plot(effect("n2p__00_nsd*AgeGroup", lm15))

lm16 <- lme(globalsignal ~ (condition + AgeGroup) * n2p__00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm16)
intervals(lm16)
plot(effect("condition*n2p__00_nsd", lm16))
plot(effect("AgeGroup*n2p__00_nsd", lm16))

# Stage 3 sleep (SWS)
lm17 <- lme(globalsignal ~ n3p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm17)
intervals(lm17)
plot(effect("n3p__00_nsd*AgeGroup", lm17))

lm18 <- lme(globalsignal ~ n3p__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm18)
intervals(lm18)
plot(effect("n3p__00_nsd*AgeGroup", lm18))

lm19 <- lme(globalsignal ~ (condition + AgeGroup) * n3p__00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm19)
intervals(lm19)
plot(effect("condition*n3p__00_nsd", lm19))
plot(effect("AgeGroup*n3p__00_nsd", lm19))

# Stage changes
lm20 <- lme(globalsignal ~ fstst00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm20)
intervals(lm20)
plot(effect("fstst00_nsd*AgeGroup", lm20))

lm21 <- lme(globalsignal ~ fstst00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm21)
intervals(lm21)
plot(effect("fstst00_nsd*AgeGroup", lm21))

lm22 <- lme(globalsignal ~ (condition + AgeGroup) * fstst00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm22)
intervals(lm22)
plot(effect("condition*fstst00_nsd", lm22))
plot(effect("AgeGroup*fstst00_nsd", lm22))

# Delta power, absolute
lm23 <- lme(globalsignal ~ delta_t_l_n3_p25_m_use_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm23)
intervals(lm23)
plot(effect("delta_t_l_n3_p25_m_use_nsd*AgeGroup", lm23))

lm24 <- lme(globalsignal ~ delta_t_l_n3_p25_m_use_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm24)
intervals(lm24)
plot(effect("delta_t_l_n3_p25_m_use_nsd*AgeGroup", lm24))

lm25 <- lme(globalsignal ~ (condition + AgeGroup) * delta_t_l_n3_p25_m_use_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm25)
intervals(lm25)
plot(effect("condition*delta_t_l_n3_p25_m_use_nsd", lm25))
plot(effect("AgeGroup*delta_t_l_n3_p25_m_use_nsd", lm25))

# Delta power, relative
lm23b <- lme(globalsignal ~ delta_t_n3_p25_m_use_nsd/totpow_n3_p25_m_use_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm23b)
intervals(lm23b)
#plot(effect("delta_t_n3_p25_m_use_nsd/totpow_n3_p25_m_use_nsd*AgeGroup", lm23b))

lm24b <- lme(globalsignal ~ delta_t_n3_p25_m_use_nsd/totpow_n3_p25_m_use_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm24b)
intervals(lm24b)
#plot(effect("delta_t_n3_p25_m_use_nsd/totpow_n3_p25_m_use_nsd*AgeGroup", lm24b))

lm25c <- lme(globalsignal ~ (condition + AgeGroup) * delta_t_n3_p25_m_use_nsd/totpow_n3_p25_m_use_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm25c)
intervals(lm25c)
#plot(effect("condition*delta_t_n3_p25_m_use_nsd/totpow_n3_p25_m_use_nsd", lm25c))
#plot(effect("AgeGroup*delta_t_n3_p25_m_use_nsd/totpow_n3_p25_m_use_nsd", lm25c))

# Number of awakenings
lm26 <- lme(globalsignal ~ fw___00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm26)
intervals(lm26)
plot(effect("fw___00_nsd*AgeGroup", lm26))

lm27 <- lme(globalsignal ~ fw___00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm27)
intervals(lm27)
plot(effect("fw___00_nsd*AgeGroup", lm27))

lm28 <- lme(globalsignal ~ (condition + AgeGroup) * fw___00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm28)
intervals(lm28)
plot(effect("condition*fw___00_nsd", lm28))
plot(effect("AgeGroup*fw___00_nsd", lm28))

# Sleep efficiency
lm29 <- lme(globalsignal ~ eff__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm29)
intervals(lm29)
plot(effect("eff__00_nsd*AgeGroup", lm29))

lm30 <- lme(globalsignal ~ eff__00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm30)
intervals(lm30)
plot(effect("eff__00_nsd*AgeGroup", lm30))

lm31 <- lme(globalsignal ~ (condition + AgeGroup) * eff__00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm31)
intervals(lm31)
plot(effect("condition*eff__00_nsd", lm31))
plot(effect("AgeGroup*eff__00_nsd", lm31))

# WASO
lm32 <- lme(globalsignal ~ waso_00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm32)
intervals(lm32)
plot(effect("waso_00_nsd*AgeGroup", lm32))

lm33 <- lme(globalsignal ~ waso_00_nsd * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm33)
intervals(lm33)
plot(effect("waso_00_nsd*AgeGroup", lm33))

lm34 <- lme(globalsignal ~ (condition + AgeGroup) * waso_00_nsd + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm34)
intervals(lm34)
plot(effect("condition*waso_00_nsd", lm34))
plot(effect("AgeGroup*waso_00_nsd", lm34))

# ISI
lm35 <- lme(globalsignal ~ ISI * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm35)
intervals(lm35)
plot(effect("ISI*AgeGroup", lm35))

lm36 <- lme(globalsignal ~ ISI * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm36)
intervals(lm36)
plot(effect("ISI*AgeGroup", lm36))

lm37 <- lme(globalsignal ~ (condition + AgeGroup) * ISI + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm37)
intervals(lm37)
plot(effect("condition*ISI", lm37))
plot(effect("AgeGroup*ISI", lm37))


# ESS
lm38 <- lme(globalsignal ~ ESS * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm38)
intervals(lm38)
plot(effect("ESS*AgeGroup", lm38))

lm39 <- lme(globalsignal ~ ESS * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm39)
intervals(lm39)
plot(effect("ESS*AgeGroup", lm39))

lm40 <- lme(globalsignal ~ (condition + AgeGroup) * ESS + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm40)
intervals(lm40)
plot(effect("condition*ESS", lm40))
plot(effect("AgeGroup*ESS", lm40))


# KSQ sleep quality
lm41 <- lme(globalsignal ~ KSQ_SleepQualityIndex * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "fullsleep"), random = ~1|ID, na.action = na.omit)
summary(lm41)
intervals(lm41)
plot(effect("KSQ_SleepQualityIndex*AgeGroup", lm41))

lm42 <- lme(globalsignal ~ KSQ_SleepQualityIndex * AgeGroup + FD, data = subset(data_glob, data_glob$condition == "sleepdeprived"), random = ~1|ID, na.action = na.omit)
summary(lm42)
intervals(lm42)
plot(effect("KSQ_SleepQualityIndex*AgeGroup", lm42))

lm43 <- lme(globalsignal ~ (condition + AgeGroup) * KSQ_SleepQualityIndex + FD, data = subset(data_glob), random = ~1|ID, na.action = na.omit)
summary(lm43)
intervals(lm43)
plot(effect("condition*KSQ_SleepQualityIndex", lm43))
plot(effect("AgeGroup*KSQ_SleepQualityIndex", lm43))


# Make table with results from above analyses
outtable2 <- data.frame(variable = "KSS main effect",
                       estimate_fullsleep = paste(round(intervals(lm2)$fixed[2, 2], 3), " [", round(intervals(lm2)$fixed[2, 1], 3), ", ", round(intervals(lm2)$fixed[2, 3], 3), "]", sep = ""), 
                       p_fullsleep = summary(lm2)$tTable[2, 5],
                       estimate_sleepdeprived = paste(round(intervals(lm3)$fixed[2, 2], 3), " [", round(intervals(lm3)$fixed[2, 1], 3), ", ", round(intervals(lm3)$fixed[2, 3], 3), "]", sep = ""), 
                       p_sleepdeprived = summary(lm3)$tTable[2, 5],
                       estimate_bothconditions = paste(round(intervals(lm4)$fixed[4, 2], 3), " [", round(intervals(lm4)$fixed[4, 1], 3), ", ", round(intervals(lm4)$fixed[4, 3], 3), "]", sep = ""), 
                       p_bothconditions = summary(lm4)$tTable[4, 5])
outtable2 <- rbind(outtable2, data.frame(variable = "KSS-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm2)$fixed[5, 2], 3), " [", round(intervals(lm2)$fixed[5, 1], 3), ", ", round(intervals(lm2)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm2)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm3)$fixed[5, 2], 3), " [", round(intervals(lm3)$fixed[5, 1], 3), ", ", round(intervals(lm3)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm3)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm4)$fixed[7, 2], 3), " [", round(intervals(lm4)$fixed[7, 1], 3), ", ", round(intervals(lm4)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm4)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "TST main effect",
                                       estimate_fullsleep = paste(round(intervals(lm5)$fixed[2, 2], 3), " [", round(intervals(lm5)$fixed[2, 1], 3), ", ", round(intervals(lm5)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm5)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm6)$fixed[2, 2], 3), " [", round(intervals(lm6)$fixed[2, 1], 3), ", ", round(intervals(lm6)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm6)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm7)$fixed[4, 2], 3), " [", round(intervals(lm7)$fixed[4, 1], 3), ", ", round(intervals(lm7)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm7)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "TST-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm5)$fixed[5, 2], 3), " [", round(intervals(lm5)$fixed[5, 1], 3), ", ", round(intervals(lm5)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm5)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm6)$fixed[5, 2], 3), " [", round(intervals(lm6)$fixed[5, 1], 3), ", ", round(intervals(lm6)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm6)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm7)$fixed[7, 2], 3), " [", round(intervals(lm7)$fixed[7, 1], 3), ", ", round(intervals(lm7)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm7)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "REM main effect",
                                       estimate_fullsleep = paste(round(intervals(lm8)$fixed[2, 2], 3), " [", round(intervals(lm8)$fixed[2, 1], 3), ", ", round(intervals(lm8)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm8)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm9)$fixed[2, 2], 3), " [", round(intervals(lm9)$fixed[2, 1], 3), ", ", round(intervals(lm9)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm9)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm10)$fixed[4, 2], 3), " [", round(intervals(lm10)$fixed[4, 1], 3), ", ", round(intervals(lm10)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm10)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "REM-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm8)$fixed[5, 2], 3), " [", round(intervals(lm8)$fixed[5, 1], 3), ", ", round(intervals(lm8)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm8)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm9)$fixed[5, 2], 3), " [", round(intervals(lm9)$fixed[5, 1], 3), ", ", round(intervals(lm9)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm9)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm10)$fixed[7, 2], 3), " [", round(intervals(lm10)$fixed[7, 1], 3), ", ", round(intervals(lm10)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm10)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "Stage 1 main effect",
                                       estimate_fullsleep = paste(round(intervals(lm11)$fixed[2, 2], 3), " [", round(intervals(lm11)$fixed[2, 1], 3), ", ", round(intervals(lm11)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm11)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm12)$fixed[2, 2], 3), " [", round(intervals(lm12)$fixed[2, 1], 3), ", ", round(intervals(lm12)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm12)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm13)$fixed[4, 2], 3), " [", round(intervals(lm13)$fixed[4, 1], 3), ", ", round(intervals(lm13)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm13)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Stage 1-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm11)$fixed[5, 2], 3), " [", round(intervals(lm11)$fixed[5, 1], 3), ", ", round(intervals(lm11)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm11)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm12)$fixed[5, 2], 3), " [", round(intervals(lm12)$fixed[5, 1], 3), ", ", round(intervals(lm12)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm12)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm13)$fixed[7, 2], 3), " [", round(intervals(lm13)$fixed[7, 1], 3), ", ", round(intervals(lm13)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm13)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "Stage 2 main effect",
                                       estimate_fullsleep = paste(round(intervals(lm14)$fixed[2, 2], 3), " [", round(intervals(lm14)$fixed[2, 1], 3), ", ", round(intervals(lm14)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm14)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm15)$fixed[2, 2], 3), " [", round(intervals(lm15)$fixed[2, 1], 3), ", ", round(intervals(lm15)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm15)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm16)$fixed[4, 2], 3), " [", round(intervals(lm16)$fixed[4, 1], 3), ", ", round(intervals(lm16)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm16)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Stage 2-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm14)$fixed[5, 2], 3), " [", round(intervals(lm14)$fixed[5, 1], 3), ", ", round(intervals(lm14)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm14)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm15)$fixed[5, 2], 3), " [", round(intervals(lm15)$fixed[5, 1], 3), ", ", round(intervals(lm15)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm15)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm16)$fixed[7, 2], 3), " [", round(intervals(lm16)$fixed[7, 1], 3), ", ", round(intervals(lm16)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm16)$tTable[7, 5]))


outtable2 <- rbind(outtable2, data.frame(variable = "Stage 3 main effect",
                                       estimate_fullsleep = paste(round(intervals(lm23)$fixed[2, 2], 3), " [", round(intervals(lm23)$fixed[2, 1], 3), ", ", round(intervals(lm23)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm18)$fixed[2, 2], 3), " [", round(intervals(lm18)$fixed[2, 1], 3), ", ", round(intervals(lm18)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm18)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm19)$fixed[4, 2], 3), " [", round(intervals(lm19)$fixed[4, 1], 3), ", ", round(intervals(lm19)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm19)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Stage 3-age group interaction",
                                       estimate_fullsleep = paste(round(intervals(lm23)$fixed[5, 2], 3), " [", round(intervals(lm23)$fixed[5, 1], 3), ", ", round(intervals(lm23)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm18)$fixed[5, 2], 3), " [", round(intervals(lm18)$fixed[5, 1], 3), ", ", round(intervals(lm18)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm18)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm19)$fixed[7, 2], 3), " [", round(intervals(lm19)$fixed[7, 1], 3), ", ", round(intervals(lm19)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm19)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "Stage changes main effect",
                                       estimate_fullsleep = paste(round(intervals(lm20)$fixed[2, 2], 3), " [", round(intervals(lm20)$fixed[2, 1], 3), ", ", round(intervals(lm20)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm20)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm21)$fixed[2, 2], 3), " [", round(intervals(lm21)$fixed[2, 1], 3), ", ", round(intervals(lm21)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm21)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm22)$fixed[4, 2], 3), " [", round(intervals(lm22)$fixed[4, 1], 3), ", ", round(intervals(lm22)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm22)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Stage changes interaction",
                                       estimate_fullsleep = paste(round(intervals(lm20)$fixed[5, 2], 3), " [", round(intervals(lm20)$fixed[5, 1], 3), ", ", round(intervals(lm20)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm20)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm21)$fixed[5, 2], 3), " [", round(intervals(lm21)$fixed[5, 1], 3), ", ", round(intervals(lm21)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm21)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm22)$fixed[7, 2], 3), " [", round(intervals(lm22)$fixed[7, 1], 3), ", ", round(intervals(lm22)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm22)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "Delta power (absolute) main effect",
                                       estimate_fullsleep = paste(round(intervals(lm23)$fixed[2, 2], 3), " [", round(intervals(lm23)$fixed[2, 1], 3), ", ", round(intervals(lm23)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm24)$fixed[2, 2], 3), " [", round(intervals(lm24)$fixed[2, 1], 3), ", ", round(intervals(lm24)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm24)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm25)$fixed[4, 2], 3), " [", round(intervals(lm25)$fixed[4, 1], 3), ", ", round(intervals(lm25)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm25)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Delta power (absolute) interaction",
                                       estimate_fullsleep = paste(round(intervals(lm23)$fixed[5, 2], 3), " [", round(intervals(lm23)$fixed[5, 1], 3), ", ", round(intervals(lm23)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm24)$fixed[5, 2], 3), " [", round(intervals(lm24)$fixed[5, 1], 3), ", ", round(intervals(lm24)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm24)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm25)$fixed[7, 2], 3), " [", round(intervals(lm25)$fixed[7, 1], 3), ", ", round(intervals(lm25)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm25)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "Delta power (relative) main effect",
                                       estimate_fullsleep = paste(round(intervals(lm23b)$fixed[2, 2], 3), " [", round(intervals(lm23b)$fixed[2, 1], 3), ", ", round(intervals(lm23b)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23b)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm24b)$fixed[2, 2], 3), " [", round(intervals(lm24b)$fixed[2, 1], 3), ", ", round(intervals(lm24b)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm24b)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm25b)$fixed[4, 2], 3), " [", round(intervals(lm25b)$fixed[4, 1], 3), ", ", round(intervals(lm25b)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm25b)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Delta power (relative) interaction",
                                       estimate_fullsleep = paste(round(intervals(lm23b)$fixed[5, 2], 3), " [", round(intervals(lm23b)$fixed[5, 1], 3), ", ", round(intervals(lm23b)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm23b)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm24b)$fixed[5, 2], 3), " [", round(intervals(lm24b)$fixed[5, 1], 3), ", ", round(intervals(lm24b)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm24b)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm25b)$fixed[7, 2], 3), " [", round(intervals(lm25b)$fixed[7, 1], 3), ", ", round(intervals(lm25b)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm25b)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "Number of awakenings main effect",
                                       estimate_fullsleep = paste(round(intervals(lm26)$fixed[2, 2], 3), " [", round(intervals(lm26)$fixed[2, 1], 3), ", ", round(intervals(lm26)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm26)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm27)$fixed[2, 2], 3), " [", round(intervals(lm27)$fixed[2, 1], 3), ", ", round(intervals(lm27)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm27)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm28)$fixed[4, 2], 3), " [", round(intervals(lm28)$fixed[4, 1], 3), ", ", round(intervals(lm28)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm28)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Number of awakenings interaction",
                                       estimate_fullsleep = paste(round(intervals(lm26)$fixed[5, 2], 3), " [", round(intervals(lm26)$fixed[5, 1], 3), ", ", round(intervals(lm26)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm26)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm27)$fixed[5, 2], 3), " [", round(intervals(lm27)$fixed[5, 1], 3), ", ", round(intervals(lm27)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm27)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm28)$fixed[7, 2], 3), " [", round(intervals(lm28)$fixed[7, 1], 3), ", ", round(intervals(lm28)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm28)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "Sleep efficiency main effect",
                                       estimate_fullsleep = paste(round(intervals(lm29)$fixed[2, 2], 3), " [", round(intervals(lm29)$fixed[2, 1], 3), ", ", round(intervals(lm29)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm29)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm30)$fixed[2, 2], 3), " [", round(intervals(lm30)$fixed[2, 1], 3), ", ", round(intervals(lm30)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm30)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm31)$fixed[4, 2], 3), " [", round(intervals(lm31)$fixed[4, 1], 3), ", ", round(intervals(lm31)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm31)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Sleep efficiency interaction",
                                       estimate_fullsleep = paste(round(intervals(lm29)$fixed[5, 2], 3), " [", round(intervals(lm29)$fixed[5, 1], 3), ", ", round(intervals(lm29)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm29)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm30)$fixed[5, 2], 3), " [", round(intervals(lm30)$fixed[5, 1], 3), ", ", round(intervals(lm30)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm30)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm31)$fixed[7, 2], 3), " [", round(intervals(lm31)$fixed[7, 1], 3), ", ", round(intervals(lm31)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm31)$tTable[7, 5]))

outtable2 <- rbind(outtable2, data.frame(variable = "Wake after sleep onset main effect",
                                       estimate_fullsleep = paste(round(intervals(lm32)$fixed[2, 2], 3), " [", round(intervals(lm32)$fixed[2, 1], 3), ", ", round(intervals(lm32)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm32)$tTable[2, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm33)$fixed[2, 2], 3), " [", round(intervals(lm33)$fixed[2, 1], 3), ", ", round(intervals(lm33)$fixed[2, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm33)$tTable[2, 5],
                                       estimate_bothconditions = paste(round(intervals(lm34)$fixed[4, 2], 3), " [", round(intervals(lm34)$fixed[4, 1], 3), ", ", round(intervals(lm34)$fixed[4, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm34)$tTable[4, 5]))
outtable2 <- rbind(outtable2, data.frame(variable = "Wake after sleep onset interaction",
                                       estimate_fullsleep = paste(round(intervals(lm32)$fixed[5, 2], 3), " [", round(intervals(lm32)$fixed[5, 1], 3), ", ", round(intervals(lm32)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_fullsleep = summary(lm32)$tTable[5, 5],
                                       estimate_sleepdeprived = paste(round(intervals(lm33)$fixed[5, 2], 3), " [", round(intervals(lm33)$fixed[5, 1], 3), ", ", round(intervals(lm33)$fixed[5, 3], 3), "]", sep = ""), 
                                       p_sleepdeprived = summary(lm33)$tTable[5, 5],
                                       estimate_bothconditions = paste(round(intervals(lm34)$fixed[7, 2], 3), " [", round(intervals(lm34)$fixed[7, 1], 3), ", ", round(intervals(lm34)$fixed[7, 3], 3), "]", sep = ""), 
                                       p_bothconditions = summary(lm34)$tTable[7, 5]))



outtable2$p_fullsleep[outtable2$p_fullsleep > 0.01] <- round(outtable2$p_fullsleep[outtable2$p_fullsleep > 0.01], 2)
outtable2$p_sleepdeprived[outtable2$p_sleepdeprived > 0.01] <- round(outtable2$p_sleepdeprived[outtable2$p_sleepdeprived > 0.01], 2)
outtable2$p_bothconditions[outtable2$p_bothconditions > 0.001] <- round(outtable2$p_bothconditions[outtable2$p_bothconditions > 0.001], 3)

print.xtable(xtable(outtable2), include.rownames = F, type="html", file="GS_covariates2.html")