# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- read_csv("~/Desktop/SleepyBrain-Analyses/Sleepmeasures_emotion/SEM_Singer_standardized.csv") ;
model<-"
! regressions 
Empathy=~1.0*Mean_ACC
Empathy=~1.0*Mean_AI
Emotional_regulation=~1.0*Mean_amygdala_down
Emotional_regulation=~1.0*Mean_lOFC
Emotional_regulation=~1.0*Mean_dlPFC
Emotional_contagion=~1.0*FFA_angry
Emotional_contagion=~1.0*FFA_happy
Emotional_contagion=~1.0*Amygdala_angry
Emotional_contagion=~1.0*Amygdala_happy
! residuals, variances and covariances
Emotional_contagion ~~ VAR_Emotional_contagion*Emotional_contagion
Empathy ~~ VAR_Empathy*Empathy
Emotional_contagion ~~ COV_Emotional_contagion_Empathy*Empathy
Mean_AI ~~ VAR_Mean_AI*Mean_AI
Mean_ACC ~~ VAR_Mean_ACC*Mean_ACC
Amygdala_happy ~~ VAR_Amygdala_happy*Amygdala_happy
Amygdala_angry ~~ VAR_Amygdala_angry*Amygdala_angry
Emotional_regulation ~~ VAR_Emotional_regulation*Emotional_regulation
Empathy ~~ COV_Empathy_Emotional_regulation*Emotional_regulation
Emotional_regulation ~~ COV_Emotional_regulation_Emotional_contagion*Emotional_contagion
FFA_happy ~~ VAR_FFA_happy*FFA_happy
FFA_angry ~~ VAR_FFA_angry*FFA_angry
Mean_amygdala_down ~~ VAR_Mean_amygdala_down*Mean_amygdala_down
Mean_lOFC ~~ VAR_Mean_lOFC*Mean_lOFC
Mean_dlPFC ~~ VAR_Mean_dlPFC*Mean_dlPFC
! observed means
Mean_AI~1;
Mean_ACC~1;
Amygdala_happy~1;
Amygdala_angry~1;
FFA_happy~1;
FFA_angry~1;
Mean_amygdala_down~1;
Mean_lOFC~1;
Mean_dlPFC~1;
";
result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result, fit.measures=TRUE);