#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- read_csv("~/Desktop/SleepyBrain-Analyses/Sleepmeasures_emotion/SEM_Singer_standardized.csv") ;
model<-"
! regressions 
EMG_mimicry=~1.0*diff_zyg
EMG_mimicry=~1.0*diff_corr
Ratings_contagion=~1.0*Angriness_angry
Ratings_contagion=~1.0*Happiness_happy
Brain_responses_ER=~1.0*FFA_angry
Brain_responses_ER=~1.0*FFA_happy
Brain_responses_ER=~1.0*Amygdala_angry
Brain_responses_ER=~1.0*Amygdala_happy
Brain_responses_E=~1.0*Mean_AI
Brain_responses_E=~1.0*Mean_ACC
Brain_responses_EC=~1.0*Mean_amygdala_down
Brain_responses_EC=~1.0*Mean_lOFC
Brain_responses_EC=~1.0*Mean_dlPFC
Rated_sucess=~1.0*DownregulateNegative
Rated_sucess=~1.0*UpregulateNegative
ratings_empathy=~1.0*IRI_EC
ratings_empathy=~1.0*Mean_unpleasantness
Emotional_contagion=~1.0*EMG_mimicry
Emotional_contagion=~1.0*Ratings_contagion
Emotional_contagion=~1.0*Brain_responses_ER
Empathy=~1.0*Brain_responses_E
Emotional_regulation=~1.0*Brain_responses_EC
Emotional_regulation=~1.0*Rated_sucess
Empathy=~1.0*ratings_empathy
! residuals, variances and covariances
Emotional_contagion ~~ VAR_Emotional_contagion*Emotional_contagion
Empathy ~~ VAR_Empathy*Empathy
Angriness_angry ~~ VAR_Rated_angriness*Angriness_angry
Emotional_contagion ~~ COV_Emotional_contagion_Empathy*Empathy
Happiness_happy ~~ VAR_Rated_happiness*Happiness_happy
diff_corr ~~ VAR_EMG_corr*diff_corr
diff_zyg ~~ VAR_EMG_zyg*diff_zyg
Mean_unpleasantness ~~ VAR_Mean_unpleasantness*Mean_unpleasantness
Mean_AI ~~ VAR_Mean_AI*Mean_AI
Mean_ACC ~~ VAR_Mean_ACC*Mean_ACC
Amygdala_happy ~~ VAR_Amygdala_happy*Amygdala_happy
Amygdala_angry ~~ VAR_Amygdala_angry*Amygdala_angry
Emotional_regulation ~~ VAR_Emotional_regulation*Emotional_regulation
Empathy ~~ COV_Empathy_Emotional_regulation*Emotional_regulation
Emotional_regulation ~~ COV_Emotional_regulation_Emotional_contagion*Emotional_contagion
FFA_happy ~~ VAR_FFA_happy*FFA_happy
FFA_angry ~~ VAR_FFA_angry*FFA_angry
EMG_mimicry ~~ VAR_EMG_mimicry*EMG_mimicry
Ratings_contagion ~~ VAR_Ratings_contagion*Ratings_contagion
Brain_responses_ER ~~ VAR_Brain_responses*Brain_responses_ER
Brain_responses_E ~~ VAR_Brain_responses*Brain_responses_E
Brain_responses_EC ~~ VAR_Brain_responses*Brain_responses_EC
Mean_amygdala_down ~~ VAR_Mean_amygdala_down*Mean_amygdala_down
Mean_lOFC ~~ VAR_Mean_lOFC*Mean_lOFC
Mean_dlPFC ~~ VAR_Mean_dlPFC*Mean_dlPFC
Rated_sucess ~~ VAR_Rated_sucess*Rated_sucess
DownregulateNegative ~~ VAR_DownregulateNegative*DownregulateNegative
UpregulateNegative ~~ VAR_UpregulateNegative*UpregulateNegative
IRI_EC ~~ VAR_IRI_EC*IRI_EC
ratings_empathy ~~ VAR_ratings_empathy*ratings_empathy
Emotional_contagion ~~ 0.0*Brain_responses_E
Emotional_contagion ~~ 0.0*Brain_responses_EC
Emotional_contagion ~~ 0.0*Rated_sucess
Emotional_contagion ~~ 0.0*ratings_empathy
Empathy ~~ 0.0*EMG_mimicry
Empathy ~~ 0.0*Ratings_contagion
Empathy ~~ 0.0*Brain_responses_ER
Empathy ~~ 0.0*Brain_responses_EC
Empathy ~~ 0.0*Rated_sucess
Emotional_regulation ~~ 0.0*EMG_mimicry
Emotional_regulation ~~ 0.0*Ratings_contagion
Emotional_regulation ~~ 0.0*Brain_responses_ER
Emotional_regulation ~~ 0.0*Brain_responses_E
Emotional_regulation ~~ 0.0*ratings_empathy
EMG_mimicry ~~ 0.0*Ratings_contagion
EMG_mimicry ~~ 0.0*Brain_responses_ER
EMG_mimicry ~~ 0.0*Brain_responses_E
EMG_mimicry ~~ 0.0*Brain_responses_EC
EMG_mimicry ~~ 0.0*Rated_sucess
EMG_mimicry ~~ 0.0*ratings_empathy
Ratings_contagion ~~ 0.0*Brain_responses_ER
Ratings_contagion ~~ 0.0*Brain_responses_E
Ratings_contagion ~~ 0.0*Brain_responses_EC
Ratings_contagion ~~ 0.0*Rated_sucess
Ratings_contagion ~~ 0.0*ratings_empathy
Brain_responses_ER ~~ 0.0*Brain_responses_E
Brain_responses_ER ~~ 0.0*Brain_responses_EC
Brain_responses_ER ~~ 0.0*Rated_sucess
Brain_responses_ER ~~ 0.0*ratings_empathy
Brain_responses_E ~~ 0.0*Brain_responses_EC
Brain_responses_E ~~ 0.0*Rated_sucess
Brain_responses_E ~~ 0.0*ratings_empathy
Brain_responses_EC ~~ 0.0*Rated_sucess
Brain_responses_EC ~~ 0.0*ratings_empathy
Rated_sucess ~~ 0.0*ratings_empathy
! observed means
Angriness_angry~1;
Happiness_happy~1;
diff_corr~1;
diff_zyg~1;
Mean_unpleasantness~1;
Mean_AI~1;
Mean_ACC~1;
Amygdala_happy~1;
Amygdala_angry~1;
FFA_happy~1;
FFA_angry~1;
Mean_amygdala_down~1;
Mean_lOFC~1;
Mean_dlPFC~1;
DownregulateNegative~1;
UpregulateNegative~1;
IRI_EC~1;
";
result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result, fit.measures=TRUE);

fit <- lavaan:::cfa(model, data = modelData, std.lv = TRUE)

# Plot path diagram:
semPaths(fit, title = FALSE, curvePivot = TRUE)
