#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- read.table(DATAFILENAME, header = TRUE) ;
 model<-"
! regressions 
   EMG_EC=~1.0*zyg
   EMG_EC=~1.0*corr
   Ratings_EC=~1.0*C_Ang
   Ratings_EC=~1.0*C_hap
   Brain_EC=~1.0*FFA_a
   Brain_EC=~1.0*FFA_ha
   Brain_EC=~1.0*Amy_an
   Brain_EC=~1.0*Amy_ha
   Brain_Ep=~1.0*AI
   Brain_Ep=~1.0*ACC
   Brain_ER=~1.0*Amy_do
   Brain_ER=~1.0*lOFC
   Brain_ER=~1.0*dlPFC
   Ratings_ER=~1.0*Downr
   Ratings_ER=~1.0*Upreg
   Ratings_Ep=~1.0*Unp
   EC=~1.0*EMG_EC
   EC=~1.0*Ratings_EC
   EC=~1.0*Brain_EC
   Ep=~1.0*Brain_Ep
   ER=~1.0*Brain_ER
   ER=~1.0*Ratings_ER
   Ep=~1.0*Ratings_Ep
! residuals, variances and covariances
   EC ~~ VAR_Emotional_contagion*EC
   Ep ~~ VAR_Empathy*Ep
   C_Ang ~~ VAR_Rated_angriness*C_Ang
   EC ~~ COV_Emotional_contagion_Empathy*Ep
   C_hap ~~ VAR_Rated_happiness*C_hap
   corr ~~ VAR_EMG_corr*corr
   zyg ~~ VAR_EMG_zyg*zyg
   Unp ~~ VAR_Mean_unpleasantness*Unp
   AI ~~ VAR_Mean_AI*AI
   ACC ~~ VAR_Mean_ACC*ACC
   Amy_ha ~~ VAR_Amygdala_happy*Amy_ha
   Amy_an ~~ VAR_Amygdala_angry*Amy_an
   ER ~~ VAR_Emotional_regulation*ER
   Ep ~~ COV_Empathy_Emotional_regulation*ER
   ER ~~ COV_Emotional_regulation_Emotional_contagion*EC
   FFA_ha ~~ VAR_FFA_happy*FFA_ha
   FFA_a ~~ VAR_FFA_angry*FFA_a
   EMG_EC ~~ VAR_EMG_mimicry*EMG_EC
   Ratings_EC ~~ VAR_Ratings_contagion*Ratings_EC
   Brain_EC ~~ VAR_Brain_responses*Brain_EC
   Brain_Ep ~~ VAR_Brain_responses*Brain_Ep
   Brain_ER ~~ VAR_Brain_responses*Brain_ER
   Amy_do ~~ VAR_Mean_amygdala_down*Amy_do
   lOFC ~~ VAR_Mean_lOFC*lOFC
   dlPFC ~~ VAR_Mean_dlPFC*dlPFC
   Ratings_ER ~~ VAR_Rated_sucess*Ratings_ER
   Downr ~~ VAR_DownregulateNegative*Downr
   Upreg ~~ VAR_UpregulateNegative*Upreg
   Ratings_Ep ~~ VAR_ratings_empathy*Ratings_Ep
   EC ~~ 0.0*Brain_Ep
   EC ~~ 0.0*Brain_ER
   EC ~~ 0.0*Ratings_ER
   EC ~~ 0.0*Ratings_Ep
   Ep ~~ 0.0*EMG_EC
   Ep ~~ 0.0*Ratings_EC
   Ep ~~ 0.0*Brain_EC
   Ep ~~ 0.0*Brain_ER
   Ep ~~ 0.0*Ratings_ER
   ER ~~ 0.0*EMG_EC
   ER ~~ 0.0*Ratings_EC
   ER ~~ 0.0*Brain_EC
   ER ~~ 0.0*Brain_Ep
   ER ~~ 0.0*Ratings_Ep
   EMG_EC ~~ 0.0*Ratings_EC
   EMG_EC ~~ 0.0*Brain_EC
   EMG_EC ~~ 0.0*Brain_Ep
   EMG_EC ~~ 0.0*Brain_ER
   EMG_EC ~~ 0.0*Ratings_ER
   EMG_EC ~~ 0.0*Ratings_Ep
   Ratings_EC ~~ 0.0*Brain_EC
   Ratings_EC ~~ 0.0*Brain_Ep
   Ratings_EC ~~ 0.0*Brain_ER
   Ratings_EC ~~ 0.0*Ratings_ER
   Ratings_EC ~~ 0.0*Ratings_Ep
   Brain_EC ~~ 0.0*Brain_Ep
   Brain_EC ~~ 0.0*Brain_ER
   Brain_EC ~~ 0.0*Ratings_ER
   Brain_EC ~~ 0.0*Ratings_Ep
   Brain_Ep ~~ 0.0*Brain_ER
   Brain_Ep ~~ 0.0*Ratings_ER
   Brain_Ep ~~ 0.0*Ratings_Ep
   Brain_ER ~~ 0.0*Ratings_ER
   Brain_ER ~~ 0.0*Ratings_Ep
   Ratings_ER ~~ 0.0*Ratings_Ep
! observed means
   C_Ang~1;
   C_hap~1;
   corr~1;
   zyg~1;
   Unp~1;
   AI~1;
   ACC~1;
   Amy_ha~1;
   Amy_an~1;
   FFA_ha~1;
   FFA_a~1;
   Amy_do~1;
   lOFC~1;
   dlPFC~1;
   Downr~1;
   Upreg~1;
";
result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result, fit.measures=TRUE);