#
# This model specification was automatically generated by Onyx
#
library(lavaan);
library(semPlot);
library(readr)
modelData <- read_csv("~/Desktop/SleepyBrain-Analyses/Sleepmeasures_emotion/SEM_Singer_standardized.csv") ;
model<-"
! regressions 
EC=~1.0*zyg
EC=~1.0*corr
EC=~1.0*C_ang
EC=~1.0*C_hap
EC=~1.0*FFA_an
EC=~1.0*FFA_ha
EC=~1.0*Amy_an
EC=~1.0*Amy_ha
Ep=~1.0*AI
Ep=~1.0*ACC
Ep=~1.0*Unp
ER=~1.0*Amy_do
ER=~1.0*lOFC
ER=~1.0*dlPFC
ER=~1.0*Downr
ER=~1.0*Upreg
! residuals, variances and covariances
EC ~~ VAR_EC*EC
Ep ~~ VAR_Ep*Ep
C_ang ~~ VAR_C_ang*C_ang
EC ~~ COV_EC_Ep*Ep
C_hap ~~ VAR_C_hap*C_hap
corr ~~ VAR_corr*corr
zyg ~~ VAR_zyg*zyg
Unp ~~ 0*Unp
AI ~~ VAR_AI*AI
ACC ~~ VAR_ACC*ACC
Amy_ha ~~ VAR_Amy_ha*Amy_ha
Amy_an ~~ VAR_Amy_an*Amy_an
ER ~~ VAR_ER*ER
Ep ~~ COV_Ep_ER*ER
ER ~~ COV_ER_EC*EC
FFA_ha ~~ VAR_FFA_ha*FFA_ha
FFA_an ~~ VAR_FFA_a*FFA_an
Amy_do ~~ VAR_Amy_do*Amy_do
lOFC ~~ VAR_lOFC*lOFC
dlPFC ~~ VAR_dlPFC*dlPFC
Downr ~~ VAR_Downr*Downr
Upreg ~~ VAR_Upreg*Upreg

! observed means
C_ang~1;
C_hap~1;
corr~1;
zyg~1;
Unp~1;
AI~1;
ACC~1;
Amy_ha~1;
Amy_an~1;
FFA_ha~1;
FFA_an~1;
Amy_do~1;
lOFC~1;
dlPFC~1;
Downr~1;
Upreg~1;
";


result<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result, fit.measures=T);
sink("Singer_SEM_all_variables_together.txt")
summary(result, fit.measures=T);
sink()


fit <- lavaan:::cfa(model, data = modelData, std.lv = TRUE)

# Plot path diagram:

semPaths(fit, intercept = F, whatLabel = "omit", nCharNodes = 0, nCharEdges =0, sizeMan = 5,
         exoVar = F,
         groups = list(c("Ep", "R_Ep", "B_Ep", "AI", "ACC", "Unp"), 
                       c("EC", "Amy_ha", "Amy_an", "C_ang", "C_hap", "FFA_an", "FFA_ha", "EMG_EC", "corr", "zyg"),
                       c("ER", "B_ER", "lOFC", "Amy_do", "dlPFC", "R_ER", "Downr", "Upreg")),
         residuals = F, exoCov = T, layout = "tree", ask = F, as.expression = "edges", fixedStyle = c("black",3),
         pastel = T, rotation = 2)

# Parameter estimates
parameterEstimates(result)
# Standardized estimates
standardizedSolution(result)
